import type { Module } from '../types';

export const week03: Module = {
  id: 'w3',
  week: 'Week 03',
  title: 'Mongoose, Frontend APIs & Code Reviews',
  tagline: 'Model data with Mongoose schemas, hydrate HTML pages from JSON APIs, and review pull requests like a professional team.',
  level: 'Intermediate',
  hue: 262,
  related: ['w2', 'w4', 'w6'],
  sections: [
    {
      id: 'mongoose',
      title: 'Mongoose: Schemas, Models & Validation',
      minutes: 40,
      blocks: [
        { type: 'lead', text: 'Mongoose is an Object Data Modeling (ODM) library that adds models, schemas, validation, and helper methods on top of MongoDB. Instead of writing every query directly against a collection, you define models that represent the important resources in your application.' },
        { type: 'h', text: 'Why use Mongoose?' },
        { type: 'p', text: 'MongoDB is flexible — but that flexibility means your application code must be careful about document shape, required fields, and validation. Without Mongoose, one product document might have productName, another might have name, and a third might accidentally leave out price. Mongoose lets your application define a predictable shape before documents are saved.' },
        { type: 'list', style: 'check', items: [
          'A schema defines the shape and rules for documents.',
          'A model gives your code methods for querying and changing documents in a collection.',
          'Mongoose can run validation before data is saved.',
          'Mongoose makes relationship fields more consistent through references.',
        ]},
        { type: 'table', title: 'MongoDB driver vs. Mongoose', headers: ['Task', 'Driver style', 'Mongoose style'], rows: [
          ['Get all products', "db.collection('products').find({}).toArray()", 'Product.find()'],
          ['Create a product', 'insertOne(productData)', 'Product.create(productData)'],
          ['Update a product', 'updateOne(filter, update)', 'Product.findByIdAndUpdate(id, data)'],
          ['Validate required fields', 'Manual validation in app code', 'Schema validation before save/update'],
        ]},
        { type: 'h', text: 'A schema with rules' },
        { type: 'code', title: 'product schema', lang: 'js', code: `import mongoose from 'mongoose';\n\nconst productSchema = new mongoose.Schema({\n  sku:      { type: String, required: true, unique: true },\n  name:     { type: String, required: true },\n  price:    { type: Number, required: true, min: 0 },\n  category: { type: String, required: true },\n  isActive: { type: Boolean, default: true }\n});\n\nconst Product = mongoose.model('Product', productSchema);\n\nexport default Product;` },
        { type: 'h', text: 'Schema field options' },
        { type: 'list', style: 'plain', items: [
          'required — the field must be present.',
          'unique — MongoDB enforces unique values through an index.',
          'default — used when the field is omitted.',
          'enum — the value must be one of a specific set of allowed values.',
          'min and max — numeric constraints.',
          'trim — remove whitespace from the start and end of a string.',
          'timestamps: true — adds createdAt and updatedAt automatically.',
        ]},
        { type: 'code', title: 'a schema using more options', lang: 'js', code: `const categorySchema = new mongoose.Schema({\n  slug:        { type: String, required: true, unique: true, trim: true },\n  displayName: { type: String, required: true, trim: true },\n  department: {\n    type: String,\n    enum: ['electronics', 'home', 'clothing', 'outdoor'],\n    required: true\n  },\n  sortOrder: { type: Number, min: 1, required: true },\n  isVisible: { type: Boolean, default: true }\n});` },
        { type: 'callout', variant: 'warn', title: 'unique is not required', body: 'unique prevents duplicate values through an index, but it does not mean the field must be present — use required for that. A duplicate value for a unique field produces a MongoDB duplicate key error (code 11000); map that conflict intentionally, often to 409 Conflict, instead of treating it as an unexpected server error.' },
        { type: 'h', text: 'Common Mongoose operations' },
        { type: 'list', style: 'plain', items: [
          'Model.find() — retrieve many documents.',
          'Model.findById(id) — retrieve one document by MongoDB _id.',
          'Model.create(data) — validate and insert a new document.',
          'Model.findByIdAndUpdate(id, data, options) — update a document.',
          'Model.findByIdAndDelete(id) — delete a document.',
        ]},
        { type: 'code', title: 'data-access functions wrapping the model', lang: 'js', code: `import Product from './product-schema.js';\n\nconst getAllProducts = async () => {\n  return Product.find().sort({ name: 1 });\n};\n\nconst getProductById = async (productId) => {\n  return Product.findById(productId);\n};\n\nconst createProduct = async (productData) => {\n  return Product.create(productData);\n};\n\nconst updateProduct = async (productId, productData) => {\n  const allowedUpdates = {};\n  if (productData.name !== undefined) allowedUpdates.name = productData.name;\n  if (productData.price !== undefined) allowedUpdates.price = productData.price;\n  if (productData.category !== undefined) allowedUpdates.category = productData.category;\n  if (productData.isActive !== undefined) allowedUpdates.isActive = productData.isActive;\n\n  return Product.findByIdAndUpdate(productId, allowedUpdates, { new: true, runValidators: true });\n};\n\nconst deleteProduct = async (productId) => {\n  return Product.findByIdAndDelete(productId);\n};\n\nexport { getAllProducts, getProductById, createProduct, updateProduct, deleteProduct };` },
        { type: 'callout', variant: 'tip', title: 'new: true and runValidators: true', body: 'new: true returns the updated document instead of the original. runValidators: true tells Mongoose to apply schema validation during updates. And building an update object from allowed fields — instead of passing the whole request body — keeps clients from writing fields they should not touch.' },
        { type: 'h', text: 'Validation errors in controllers' },
        { type: 'code', title: 'mapping Mongoose errors to status codes', lang: 'js', code: `const createProductHandler = async (req, res) => {\n  try {\n    const product = await createProduct(req.body);\n    return res.status(201).json(product);\n  } catch (error) {\n    if (error.name === 'ValidationError') {\n      return res.status(400).json({ message: 'Invalid product data' });\n    }\n    return res.status(500).json({ message: 'Internal server error' });\n  }\n};` },
        { type: 'list', style: 'check', items: [
          'ValidationError → 400 (client sent invalid data).',
          'CastError (badly formatted id) → 400.',
          'Valid id with no matching document → 404.',
          'Anything unexpected → 500 with a safe message.',
        ]},
        { type: 'h', text: 'Relationships with references and populate' },
        { type: 'code', title: 'a reference to another model', lang: 'js', code: `const productSchema = new mongoose.Schema({\n  sku:   { type: String, required: true, unique: true },\n  name:  { type: String, required: true },\n  price: { type: Number, required: true, min: 0 },\n  category: {\n    type: mongoose.Schema.Types.ObjectId,\n    ref: 'Category',\n    required: true\n  },\n  isActive: { type: Boolean, default: true }\n});` },
        { type: 'p', text: 'When a schema uses a reference, the document stores an id. Sometimes the API only needs the id; other times it should return related data. Mongoose\'s populate method replaces a referenced id with selected fields from the related document.' },
        { type: 'code', title: 'populate a reference', lang: 'js', code: `const product = await Product.findById(productId)\n  .populate('category', 'displayName slug department');` },
        { type: 'callout', variant: 'warn', title: 'Use populate carefully', body: 'populate can make responses more useful, but it means Mongoose performs additional database work. Only populate related data when the client actually needs it.' },
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'What does a Mongoose schema do?', a: 'It defines the shape and rules for documents — fields, types, required, unique, defaults, enum, min/max — and Mongoose validates data against it before saving.' },
          { q: 'What is the difference between a schema and a model?', a: 'The schema defines the rules; the model is the object that queries and changes documents in the collection (Product.find(), Product.create(), …).' },
          { q: 'How should a controller handle a Mongoose ValidationError?', a: 'Treat it as a client input problem — return 400 with a safe message rather than exposing raw validation details.' },
          { q: 'When does populate help?', a: 'When the API should return related data (e.g. category details) instead of just the referenced id. Use it only when the client needs the related fields.' },
        ]},
        { type: 'takeaways', items: [
          'Schemas define shape and rules; models query the collection.',
          'required / unique / default / enum / min / max / trim make data predictable.',
          'ValidationError → 400, CastError → 400, valid id no match → 404.',
          'References store ObjectIds; populate replaces them with related documents on demand.',
          'Choose references for shared or changing data; embed for snapshots.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: read an existing schema', level: 'Warm-up', steps: [
          'Find one existing model in a team codebase.',
          'List its schema fields, required fields, defaults, enum values, and references.',
          'Find one controller or route that uses the model.',
          'Pick one field and decide: should it be required, optional, have a default, or an enum? Defend the decision.',
          'Find where a reference to another model exists (or should exist).',
        ]},
      ],
    },
    {
      id: 'hydrating-html',
      title: 'Using Web Services to Hydrate HTML Pages',
      minutes: 35,
      blocks: [
        { type: 'lead', text: 'Instead of the server rendering every piece of content, the server can expose JSON API endpoints — and frontend JavaScript fetches that data and updates the page in place. This is the pattern that makes pages feel fast and alive.' },
        { type: 'h', text: 'Server-rendered pages vs. API-driven pages' },
        { type: 'table', headers: ['Server-rendered page', 'API-driven page'], rows: [
          ['The Express route calls res.render().', 'The Express route returns JSON with res.json().'],
          ['EJS loops over data while the page is generated.', 'Browser JavaScript loops over JSON after the page loads.'],
          ['The browser receives mostly finished HTML.', 'The browser receives data and builds part of the interface.'],
        ]},
        { type: 'p', text: 'When a page uses a web service, JavaScript can request new data and update only the section that needs to change. Searching, filtering, and paging through results happen without a full page reload — the header, navigation, and the user\'s scroll position stay in place. Your app does not need to become a single-page application to gain these benefits: keep server-rendered pages for navigation and add web-service-driven components where a small part of a page needs to respond quickly.' },
        { type: 'h', text: 'The fetch flow' },
        { type: 'code', title: 'fetch + json', lang: 'js', code: `const response = await fetch('/api/products');\nconst products = await response.json();` },
        { type: 'callout', variant: 'danger', title: 'fetch does NOT throw on 404 or 500', body: 'fetch() only rejects for network-level failures. A 404 or 500 response still produces a response object. Always check response.ok before assuming the request succeeded.' },
        { type: 'code', title: 'check response.ok', lang: 'js', code: `const loadProducts = async () => {\n  const response = await fetch('/api/products');\n\n  if (!response.ok) {\n    throw new Error('Unable to load products.');\n  }\n\n  return response.json();\n};` },
        { type: 'h', text: 'Hydrating with the HTML <template> element' },
        { type: 'p', text: 'Hydrating a page means taking data returned by a web service and using it to fill in the page\'s HTML. The HTML <template> element holds a reusable piece of markup that is not displayed until JavaScript clones it and adds it to the page.' },
        { type: 'code', title: 'template markup in the HTML', lang: 'html', code: `<section id="product-list" aria-live="polite"></section>\n\n<template id="product-card-template">\n  <article class="product-card">\n    <h3 class="product-name"></h3>\n    <p class="product-category"></p>\n    <p class="product-price"></p>\n  </article>\n</template>` },
        { type: 'code', title: 'clone, fill with textContent, render', lang: 'js', code: `const renderProducts = (products) => {\n  const productList = document.querySelector('#product-list');\n  const template = document.querySelector('#product-card-template');\n  const fragment = document.createDocumentFragment();\n\n  products.forEach((product) => {\n    const productCard = template.content.cloneNode(true);\n\n    productCard.querySelector('.product-name').textContent = product.name;\n    productCard.querySelector('.product-category').textContent = product.category;\n    productCard.querySelector('.product-price').textContent = \`$\${product.price}\`;\n\n    fragment.append(productCard);\n  });\n\n  productList.replaceChildren(fragment);\n};` },
        { type: 'p', text: 'The browser keeps template content separate from the live page until cloneNode(true) creates a copy (true includes all nested elements). A DocumentFragment collects every completed card, and replaceChildren() swaps in the new content in one operation.' },
        { type: 'callout', variant: 'warn', title: 'textContent is safer than innerHTML', body: 'Building HTML strings with innerHTML treats API values as HTML — a product name containing HTML-looking characters could inject markup or scripts (an XSS risk). Setting values with textContent keeps API text as text. Templates also keep structure in the HTML file, where it is easier to read and maintain.' },
        { type: 'h', text: 'Loading, success, and error states' },
        { type: 'list', style: 'check', items: [
          'Loading — show a visible state while the request is in flight.',
          'Success — render the data into the page.',
          'Error — show a useful message when response.ok is false or the request fails.',
          'All three states should be visible to the user; never leave a blank area guessing.',
        ]},
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'What is the difference between a server-rendered page and an API-driven page?', a: 'A server-rendered page receives HTML the server already built (res.render). An API-driven page receives data (usually JSON) and browser JavaScript renders or updates part of the page.' },
          { q: 'Why check response.ok after fetch()?', a: 'fetch resolves even when the server responds with 404 or 500. Checking response.ok lets your code recognize the failure and show an error state.' },
          { q: 'What does it mean to hydrate an HTML template?', a: 'Cloning its reusable structure and filling the clone with values returned by a web service before adding it to the live page.' },
          { q: 'Why choose <template> over building markup with innerHTML?', a: 'Templates keep structure in HTML where it is easy to read, and JavaScript sets individual values with textContent instead of treating API values as HTML.' },
          { q: 'How does a web service improve a filtered product list?', a: 'JavaScript requests the filtered results from the API and replaces only the product-list section — no full page refresh.' },
        ]},
        { type: 'takeaways', items: [
          'Server renders JSON; browser JavaScript builds the interface.',
          'Always check response.ok — fetch does not throw on HTTP errors.',
          'Clone <template> content and fill it with textContent for safe hydration.',
          'Show loading, success, and error states explicitly.',
        ]},
        { type: 'exercise', title: 'Mini-project: hydrate a list page', level: 'Core', steps: [
          'Take an existing server-rendered list page and identify the loop that renders items in EJS.',
          'Create a GET /api/items route that returns the same data as JSON.',
          'Replace the EJS loop with an empty container and a <template> for one item card.',
          'Write client-side JavaScript that fetches the API, checks response.ok, clones the template per item, and renders with textContent.',
          'Add visible loading and error states, then test by stopping the server to see the error path.',
        ]},
      ],
    },
    {
      id: 'code-reviews',
      title: 'Code Reviews',
      minutes: 30,
      blocks: [
        { type: 'lead', text: 'A code review is not a formality. It is a structured check of whether a change is understandable, correct, tested, and safe to merge — and one of the main ways professional engineers learn a codebase and protect shared systems.' },
        { type: 'h', text: 'Why code reviews matter' },
        { type: 'list', style: 'check', items: [
          'They catch bugs and missing tests before code reaches main.',
          'They help the whole team understand changes in the codebase.',
          'They improve consistency across routes, controllers, models, and documentation.',
          'They create a record of design decisions and tradeoffs.',
        ]},
        { type: 'p', text: 'Most companies require at least one code review before code can be merged into the main branch. AI is often used as a first pass to find possible issues, but most companies still require a human review before code is approved and merged.' },
        { type: 'h', text: 'What a pull request should tell you' },
        { type: 'p', text: 'Before reviewing code, read the pull request description and any GitHub issues it references. Reviewing without understanding the purpose of the change is like grading an answer without reading the question. A useful PR explains: which issue it resolves, what behavior changed, which files changed, how the author tested it, and anything the reviewer should pay special attention to.' },
        { type: 'h', text: 'The review flow' },
        { type: 'list', style: 'steps', items: [
          'Read the GitHub issue and pull request description.',
          'Check the changed files to understand the scope.',
          'Review the main route, controller, model, middleware, or frontend entry point.',
          'Compare the implementation with the test notes, Swagger docs, and expected behavior.',
          'Leave comments where you see a bug, risk, question, or useful confirmation.',
        ]},
        { type: 'h', text: 'Review checklist' },
        { type: 'list', style: 'check', items: [
          'Issue match — the change solves the issue without unrelated work.',
          'Behavior — success, failure, and edge cases behave as expected.',
          'Responses — status codes, JSON bodies, and error messages make sense.',
          'Data — schemas, validation rules, queries, and relationships fit the feature.',
          'Security — no secrets committed; protected routes have the needed checks.',
          'Documentation — Swagger docs match the implemented behavior.',
          'Testing — the PR explains what was tested and the tests match the risk.',
          'Code quality — understandable and follows existing project patterns.',
        ]},
        { type: 'h', text: 'Weak comments vs. helpful comments' },
        { type: 'table', headers: ['Weak comment', 'Helpful comment'], rows: [
          ['"This is wrong."', '"This route returns 500 when the ticket id is not found. Should it return 404 instead, since the request is valid but the ticket does not exist?"'],
          ['"Fix this."', '"Could you add runValidators: true to this update so schema validation still applies during PUT requests?"'],
          ['"Looks good."', '"I tested this in Swagger with a valid token and confirmed the route only returns tickets for the authenticated user. The response matches the docs."'],
        ]},
        { type: 'callout', variant: 'tip', title: 'Review the code, support the person', body: 'A helpful comment tells the author what you noticed, why it matters, and what kind of change or answer would resolve the concern. Good reviews are direct about the code and respectful toward the author — the goal is to help the team ship better work, not to win an argument.' },
        { type: 'h', text: 'Review outcomes' },
        { type: 'list', style: 'plain', items: [
          'Comment — feedback or questions, but not approving or blocking yet.',
          'Approve — the PR is ready to merge.',
          'Request changes — a bug, missing requirement, unsafe behavior, or other issue that must be fixed before merge. Requesting changes is not rude when done clearly and respectfully.',
        ]},
        { type: 'callout', variant: 'info', title: 'Course requirement', body: 'Each review must include at least two meaningful comments, and at least one should address behavior, testing, security, data modeling, or documentation. A review that only says "looks good" is not enough — if the PR is truly simple and correct, explain what you checked before approving.' },
        { type: 'h', text: 'Reviewing without running everything' },
        { type: 'p', text: 'Sometimes you cannot fully run a teammate\'s branch. You can still provide useful review, but be honest about what you checked: if you ran the code, say what you tested; if you only read the code, say so; if you need test notes, ask for them.' },
        { type: 'code', title: 'an honest partial review', lang: 'js', code: `"I reviewed the code changes but did not run this branch locally.\nThe schema and route wiring look consistent with the existing\nstation routes. Could you add the Swagger test results to the\nPR description before merge?"` },
        { type: 'h', text: 'After approval' },
        { type: 'list', style: 'check', items: [
          'Do not assume an approved PR is finished until it has been merged.',
          'The author generally merges their own PR after approval; remind them in the team channel.',
          'After a merge, teammates pull the latest main before starting or continuing work.',
          'Every PR needs at least one review — if a teammate\'s PR is unreviewed, help the team by reviewing it.',
        ]},
        { type: 'takeaways', items: [
          'Reviews check more than "does it run": correctness, tests, security, data modeling, docs, consistency.',
          'Helpful comments are specific, explain the risk, and ask clear questions.',
          'Outcomes: Comment, Approve, or Request changes — each is a professional signal.',
          'Be honest about what you ran versus what you only read.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: write two review comments', level: 'Warm-up', steps: [
          'Pick a small PR (a classmate\'s or an open-source one).',
          'Write one comment that identifies a bug, edge case, or docs mismatch with file/line references.',
          'Write one comment that confirms something you tested or verified.',
          'Rewrite "this is wrong" and "looks good" into helpful comments using the patterns above.',
        ]},
      ],
    },
    {
      id: 'kizuna-rail-project',
      title: 'Team Project: The Kizuna Rail Codebase',
      minutes: 45,
      blocks: [
        { type: 'lead', text: 'Week 03 moves you into a brownfield team project: Kizuna Rail, a fictional scenic railway booking site for tourists in Japan. You inherit an existing codebase — patterns, technical debt, and all — and refactor it to Mongoose plus API-driven pages.' },
        { type: 'h', text: 'Brownfield vs. greenfield' },
        { type: 'list', style: 'plain', items: [
          'Greenfield — a new project; you choose everything.',
          'Brownfield — an existing project with patterns, technical debt, and decisions you inherit.',
        ]},
        { type: 'h', text: 'Habits that make brownfield work survivable' },
        { type: 'list', style: 'check', items: [
          'Pull main before starting — stale local code causes mysterious missing features.',
          'Trace a request through the code before changing anything.',
          'Read files before editing them.',
          'Make small commits.',
          'Ask the team when confused — do not guess about inherited decisions.',
        ]},
        { type: 'h', text: 'Map of the codebase' },
        { type: 'table', headers: ['File / folder', 'Purpose'], rows: [
          ['server.js', 'Entry point — connects to MongoDB, starts the server'],
          ['app.js', 'Express config — EJS, static files, router'],
          ['src/routes/router.js', 'Top-level routes; delegates to route files'],
          ['src/db/seeds/*.json', 'Starter data (imported by npm run db:import)'],
          ['public/', 'Static assets — CSS, images, browser JS in public/js/main.js'],
        ]},
        { type: 'callout', variant: 'warn', title: 'Docs can drift from reality', body: 'In this codebase, data access was scattered across route files — there was no model.js, despite what the docs said. Always verify inherited documentation against the actual code.' },
        { type: 'h', text: 'The target architecture' },
        { type: 'p', text: 'The team refactors to a clear model-view-controller pattern with two kinds of controllers and two kinds of routes: EJS controllers render pages, and API controllers send JSON. Several pages switch to client-side hydration, and some pages keep EJS main content with dynamic sections powered by the APIs.' },
        { type: 'code', title: 'file organization', lang: 'bash', code: `src/models/schemas/trains.js        # Mongoose schemas\nsrc/models/schemas/trips.js\nsrc/models/schemas/stations.js\nsrc/models/schemas/schedules.js\nsrc/models/schemas/ticket-classes.js\nsrc/models/schemas/bookings.js\n\nsrc/models/trips.js                 # model functions (query + return)\nsrc/controllers/trips.js            # controllers (JSON or res.render)\nsrc/routes/api-routes.js            # JSON API endpoints\nsrc/routes/ejs-routes.js            # routes that render EJS pages` },
        { type: 'h', text: 'Feature sets' },
        { type: 'table', headers: ['Feature set', 'Key deliverables', 'Required?'], rows: [
          ['1 · Trips', 'Schema + getTripById/getAllTrips, /api/trips routes with Swagger, trip list page hydrated via the API', 'All teams'],
          ['2 · Schedules', 'getSchedulesByTripId with optional month, /api/trips/{id}/schedules?month=, month selector updates schedules via fetch', 'All teams'],
          ['3 · Bookings', 'Rename confirmations → bookings, createBooking/getAllBookings/getBookingById, /api/bookings, bookings admin page hydrated via API', 'All teams'],
          ['4 · Ticket classes', 'getAllTicketClasses/getTicketClassesForDay, /api/ticket-classes?day=, booking page grays out unavailable options', '4+ members'],
          ['5 · Stations', 'getAllStations/getStationById, /api/stations routes, expandable station details on the trip page via API', '5 members'],
        ]},
        { type: 'h', text: 'Team workflow' },
        { type: 'list', style: 'steps', items: [
          'Complete setup tasks: one Render deployment, one shared MongoDB Atlas cluster, connection string shared privately.',
          'Assign every feature set an owner and post the decisions in the team channel.',
          'Write a spec per feature: description, data model, endpoints, status codes, test plan.',
          'Create at least one GitHub issue per feature set.',
          'Implement on a branch, test locally, run ESLint, record a walkthrough video, open a PR linking the issue with test notes and the video link.',
          'Post the PR in the team channel as ready for review; teammates review before merge.',
        ]},
        { type: 'callout', variant: 'danger', title: 'Dependencies matter', body: 'Multiple people editing api-routes.js causes merge conflicts — the team must decide who goes first. Use a branch per feature with a clear name, push fixes to the same branch (never open a new PR for the same feature), and respond to review comments with concrete evidence: which files changed, which tests pass.' },
        { type: 'takeaways', items: [
          'Brownfield = inherited patterns and debt; trace and read before you change.',
          'Split routes into ejs-routes.js (pages) and api-routes.js (JSON endpoints).',
          'Schemas → models → controllers → routes, per resource.',
          'Coordinate owners publicly, branch per feature, review every PR before merge.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: trace a request', level: 'Core', steps: [
          'In any existing codebase, pick one page and trace the request: route → controller → data access → response.',
          'Note every file the request touches and what each file owns.',
          'Identify one place where data access logic sits in a route file — sketch how you would move it into a model function.',
          'Write the API route, controller function, and model function names you would create for that resource.',
        ]},
      ],
    },
  ],
  quiz: [
    { q: 'What is Mongoose?', options: ['A replacement database server', 'An ODM that adds schemas, models, and validation on top of MongoDB', 'An HTTP client', 'A template engine'], answer: 1, explain: 'Mongoose still uses MongoDB underneath, but gives your code a higher-level model API.' },
    { q: 'A Mongoose ValidationError in a controller should map to…', options: ['200', '400', '404', '500'], answer: 1, explain: 'Validation failures are client input problems — return 400 with a safe message.' },
    { q: 'A CastError from findById() means…', options: ['The server crashed', 'The id format is invalid → 400', 'The document was deleted → 410', 'The database is empty → 204'], answer: 1, explain: 'Invalid id format is a client input error; a valid id with no match would be 404.' },
    { q: 'What does populate(\'category\', \'displayName slug\') do?', options: ['Deletes the category', 'Replaces the referenced id with selected fields from the related document', 'Creates an index', 'Validates the schema'], answer: 1, explain: 'populate fetches the referenced document and merges the selected fields into the result.' },
    { q: 'fetch() to a missing route resolves with a 404 response. What must you do?', options: ['Nothing — fetch throws on 404', 'Check response.ok before using the data', 'Call response.text()', 'Retry automatically'], answer: 1, explain: 'fetch only rejects on network failures; HTTP errors must be detected via response.ok.' },
    { q: 'Why fill template clones with textContent instead of innerHTML?', options: ['It is faster to type', 'API values stay text instead of being parsed as HTML, avoiding XSS', 'innerHTML is deprecated', 'Templates require it'], answer: 1, explain: 'textContent never treats data as markup, which keeps API text safe.' },
    { q: 'Which is a helpful review comment?', options: ['"Looks good."', '"Fix this."', '"Could you add runValidators: true so schema validation applies on PUT?"', '"This is wrong."'], answer: 2, explain: 'Helpful comments are specific, explain the risk, and propose a concrete change or question.' },
    { q: 'A brownfield project means…', options: ['A brand-new project you design from scratch', 'An existing codebase with patterns and decisions you inherit', 'A project without a database', 'A solo assignment'], answer: 1, explain: 'Brownfield work requires tracing, reading, and respecting existing conventions.' },
  ],
};
