import type { Module } from '../types';

export const week02: Module = {
  id: 'w2',
  week: 'Week 02',
  title: 'CRUD, Relationships & Swagger',
  tagline: 'Add create, update, and delete routes; model relationships between collections; document and test everything with Swagger.',
  level: 'Beginner',
  hue: 190,
  related: ['w1', 'w3', 'w5'],
  sections: [
    {
      id: 'crud-operations',
      title: 'CRUD Operations',
      minutes: 35,
      blocks: [
        { type: 'lead', text: 'CRUD stands for Create, Read, Update, and Delete — the basic operations most data-driven applications need. This week your API stops being read-only and clients can change the data stored in MongoDB.' },
        { type: 'h', text: 'HTTP methods map to CRUD' },
        { type: 'p', text: 'In REST-style APIs, HTTP methods communicate which operation the client wants. GET reads data, POST usually creates new data, PUT replaces or updates existing data, PATCH handles partial updates, and DELETE removes data.' },
        { type: 'diagram', name: 'crud-map', caption: 'Each HTTP method maps to a CRUD action and a MongoDB operation.' },
        { type: 'table', headers: ['API action', 'HTTP method', 'MongoDB operation'], rows: [
          ['Create a product', 'POST', 'insertOne'],
          ['Read products', 'GET', 'find or findOne'],
          ['Update a product', 'PUT', 'updateOne'],
          ['Delete a product', 'DELETE', 'deleteOne'],
        ]},
        { type: 'h', text: 'POST creates a new resource' },
        { type: 'p', text: 'A POST request usually sends data in the request body. The server validates that data, inserts a new document, and returns a response telling the client what was created. MongoDB returns a result object — check insertedId to confirm the document was created.' },
        { type: 'code', title: 'POST /products request', lang: 'http', code: `POST /products\nContent-Type: application/json\n\n{\n  "id": "p4",\n  "name": "Wireless Mouse",\n  "category": "electronics",\n  "price": 24.99,\n  "inStock": true\n}` },
        { type: 'code', title: 'insertOne in the model', lang: 'js', code: `const result = await getDb()\n  .collection('products')\n  .insertOne(newProduct);\n\n// result.insertedId confirms the document was created` },
        { type: 'h', text: 'PUT updates an existing resource' },
        { type: 'p', text: 'A PUT request usually includes an id in the URL and updated data in the body. The first argument to updateOne is the filter; the second uses the $set operator to update only the specified fields. The result object includes matchedCount and modifiedCount, which help your controller decide between success and 404.' },
        { type: 'code', title: 'updateOne with $set', lang: 'js', code: `const result = await getDb()\n  .collection('products')\n  .updateOne(\n    { id: productId },\n    { $set: updatedProduct }\n  );\n\n// result.matchedCount === 0  → return 404\n// result.modifiedCount === 1 → the update happened` },
        { type: 'callout', variant: 'warn', title: 'Why use $set?', body: 'The $set operator tells MongoDB which fields to update. Without an update operator such as $set, you can accidentally replace more of the document than intended.' },
        { type: 'h', text: 'DELETE removes an existing resource' },
        { type: 'code', title: 'deleteOne', lang: 'js', code: `const result = await getDb()\n  .collection('products')\n  .deleteOne({ id: productId });\n\n// result.deletedCount === 1 → deleted, return 204\n// result.deletedCount === 0 → nothing matched, return 404` },
        { type: 'h', text: 'Check the result object before choosing a status code' },
        { type: 'list', style: 'plain', items: [
          'insertOne returns an insertedId when a document is created.',
          'updateOne returns counts such as matchedCount and modifiedCount.',
          'deleteOne returns deletedCount.',
          'matchedCount: 0 means the requested document was not found — return 404.',
        ]},
        { type: 'h', text: 'Status codes for write routes' },
        { type: 'list', style: 'plain', items: [
          '201 Created — a new document was created successfully.',
          '200 OK — an update succeeded and the API returns a body.',
          '204 No Content — an update or delete succeeded with no response body.',
          '400 Bad Request — required input is missing or invalid.',
          '404 Not Found — the requested document does not exist.',
          '500 Internal Server Error — something unexpected failed on the server.',
        ]},
        { type: 'h', text: 'Validate before you insert' },
        { type: 'p', text: 'POST and PUT requests send JSON in the body, so your Express app needs app.use(express.json()) to read it as req.body. Controllers should validate required fields before calling MongoDB — if required fields are missing or invalid, return a safe 400 response instead of letting bad data reach the database.' },
        { type: 'code', title: 'controller flow for POST /products', lang: 'js', code: `const createProduct = async (req, res) => {\n  try {\n    const { id, name, category, price, inStock } = req.body;\n\n    if (!id || !name || !category || price === undefined || inStock === undefined) {\n      return res.status(400).json({ message: 'id, name, category, price, and inStock are required' });\n    }\n\n    const newProduct = { id, name, category, price, inStock };\n    await productModel.createProduct(newProduct);\n\n    return res.status(201).json(newProduct);\n  } catch (error) {\n    return res.status(500).json({ message: 'Unable to create product' });\n  }\n};` },
        { type: 'callout', variant: 'info', title: 'Duplicate ids: pick a rule and document it', body: 'Decide how your API should handle a create request with an id that already exists. Many APIs return 409 Conflict for duplicate data, but a clear 400 response is also acceptable — as long as your spec documents the choice. The spec is the contract: the API must behave exactly as the spec says.' },
        { type: 'demo', name: 'api-simulator' },
        { type: 'qa', title: 'Trace one write route before coding', items: [
          { q: 'What method and URL does a create request use?', a: 'POST /products — the POST method tells the API the client wants to create a new product.' },
          { q: 'What validation happens before calling MongoDB?', a: 'The controller checks that each required field exists and has a reasonable value. Missing data returns 400 Bad Request before the database is touched.' },
          { q: 'Which MongoDB method creates one document?', a: 'insertOne — and the controller or model checks insertedId to confirm creation.' },
          { q: 'What status code confirms a successful create?', a: '201 Created, usually with the created object or a short confirmation message in the body.' },
        ]},
        { type: 'takeaways', items: [
          'POST → insertOne, GET → find/findOne, PUT → updateOne + $set, DELETE → deleteOne.',
          'Validate required fields in the controller before touching the database.',
          'Read the result object (insertedId, matchedCount, deletedCount) to choose 200/201/204 vs 404.',
          'Duplicate-id behavior (409 or 400) is a design decision — document it in the spec.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: trace POST /products', level: 'Warm-up', steps: [
          'On paper, trace a POST /products request from the client to MongoDB and back.',
          'Write the six checkpoints: method+URL, required body fields, validation, model method, result value, status code.',
          'Use the interactive API simulator above to send a POST with a missing field and observe the 400 response.',
          'Repeat with a duplicate id and decide whether your API returns 400 or 409 — then write that rule into a spec sentence.',
        ]},
      ],
    },
    {
      id: 'mongodb-relationships',
      title: 'Database Relationships in MongoDB',
      minutes: 30,
      blocks: [
        { type: 'lead', text: 'One collection by itself can only do so much. Real power comes when data is connected through relationships — and in MongoDB you choose whether to embed related data or reference it.' },
        { type: 'h', text: 'Embed or reference?' },
        { type: 'p', text: 'Unlike a relational database, MongoDB does not require foreign keys or table joins. Instead, you decide whether related data should be embedded inside one document or referenced from another document.' },
        { type: 'list', style: 'check', items: [
          'Use embedded data when the related information is small and usually read together — like a product\'s dimensions stored inside the product document.',
          'Use references when the related information is shared, changes independently, or belongs in its own collection.',
          'Use embedded data when you need a historical snapshot that should not change later — like the price at the time of purchase.',
        ]},
        { type: 'diagram', name: 'embed-vs-ref', caption: 'Embedding keeps data inside the parent; referencing stores only the id.' },
        { type: 'h', text: 'Example: products and categories' },
        { type: 'code', title: 'a category document', lang: 'json', code: `{\n  "id": "c1",\n  "name": "Electronics",\n  "description": "Devices, accessories, and small electronics"\n}` },
        { type: 'code', title: 'a product referencing the category', lang: 'json', code: `{\n  "id": "p4",\n  "categoryId": "c1",\n  "name": "Wireless Mouse",\n  "price": 24.99,\n  "inStock": true\n}` },
        { type: 'p', text: 'Here categoryId: "c1" means the product belongs to the category whose id is c1. MongoDB will store that value, but your API code is responsible for deciding what to do with it.' },
        { type: 'callout', variant: 'warn', title: 'References do not auto-join', body: 'If you query the products collection, MongoDB returns the product document. It does not automatically fetch the matching category document just because the product has a categoryId field. Your API either returns only the categoryId, or makes a second query to include category details.' },
        { type: 'h', text: 'More advanced joins with $lookup' },
        { type: 'p', text: 'MongoDB has more advanced ways to combine related data, such as the aggregation stage $lookup, which queries another collection and attaches matching documents to the results — similar to a join in a relational database.' },
        { type: 'code', title: 'joining categories onto products', lang: 'js', code: `const productsWithCategories = await getDb()\n  .collection('products')\n  .aggregate([\n    {\n      $lookup: {\n        from: 'categories',\n        localField: 'categoryId',\n        foreignField: 'id',\n        as: 'category'\n      }\n    }\n  ])\n  .toArray();` },
        { type: 'h', text: 'Validate relationship fields' },
        { type: 'p', text: 'When a client creates or updates a product, the API should verify the relationship. Before creating a product with categoryId: "c1", the controller or model can query the categories collection to confirm a category with id "c1" exists. If it does not, return 400 Bad Request because the request data is invalid.' },
        { type: 'h', text: 'Deleting related data' },
        { type: 'p', text: 'Relationships affect delete behavior. If a client tries to delete a category that still has products, your API must choose and document a clear rule: block the delete with an error, allow it and leave dangling references, or update related products. The safest starting choice is to block the delete when related documents still depend on that record.' },
        { type: 'qa', title: 'Think through a relationship', items: [
          { q: 'Which field on the product identifies its category?', a: 'categoryId — it stores the id of a document in the categories collection.' },
          { q: 'Should category details be embedded in each product?', a: 'A separate categories collection is better: many products share one category, and category details change independently of product details.' },
          { q: 'What if a product is created with a categoryId that does not exist?', a: 'Return 400 Bad Request — the client sent a relationship value that does not point to a valid category.' },
          { q: 'What if a client deletes a category that still has products?', a: 'Block the delete and return an error such as 400 or 409 Conflict, because deleting would leave related products with an invalid reference.' },
        ]},
        { type: 'takeaways', items: [
          'Embed for small, read-together data or snapshots; reference for shared, independently-managed data.',
          'References store an id only — you need a second query or $lookup to get related data.',
          'Validate relationship fields: reject an authorId or categoryId that does not exist.',
          'Block deletes when other documents still reference the record.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: books ↔ authors', level: 'Core', steps: [
          'Design the books and authors collections: which fields does each document have?',
          'Decide: should the author be embedded in the book, or referenced by authorId? Defend your choice in two sentences.',
          'Write the validation rule for POST /books when the submitted authorId does not exist.',
          'Write the delete rule for DELETE /authors/:id when the author still has books, including the exact status code.',
        ]},
      ],
    },
    {
      id: 'swagger-docs',
      title: 'Swagger & OpenAPI Documentation',
      minutes: 35,
      blocks: [
        { type: 'lead', text: 'Swagger is a common way to document REST APIs: routes, methods, parameters, request bodies, response bodies, and status codes. Swagger UI turns that documentation into an interactive page where you can send real requests from the browser.' },
        { type: 'h', text: 'Documentation that doubles as a testing surface' },
        { type: 'p', text: 'Good Swagger documentation is both a reference and a testing surface. If your Swagger docs are inaccurate, your tests may hide bugs or confuse API clients. The word Swagger is used for the interactive tools; the API description format itself is OpenAPI. Generate OpenAPI 3 documentation so your examples match current API documentation patterns.' },
        { type: 'h', text: 'The two packages' },
        { type: 'list', style: 'plain', items: [
          'swagger-ui-express (production dependency) — serves the interactive Swagger UI from your Express app.',
          'swagger-jsdoc (development dependency) — reads OpenAPI comments from your route files and generates swagger.json. Only needed when generating docs, so it is a dev dependency.',
        ]},
        { type: 'code', title: 'install', lang: 'bash', code: `npm install swagger-ui-express\nnpm install --save-dev swagger-jsdoc` },
        { type: 'h', text: 'The generation process' },
        { type: 'diagram', name: 'swagger-flow', caption: '@openapi comments → swagger-jsdoc → swagger.json → Swagger UI at /api-docs.' },
        { type: 'code', title: 'swagger.js — the generator', lang: 'js', code: `import { writeFileSync } from 'node:fs';\nimport swaggerJsdoc from 'swagger-jsdoc';\n\nconst options = {\n  definition: {\n    openapi: '3.0.0',\n    info: {\n      title: 'Books API',\n      version: '1.0.0',\n      description: 'A simple API for working with books'\n    },\n    servers: [{ url: '/', description: 'Current server' }]\n  },\n  apis: ['./src/router.js', './app.js']\n};\n\nconst swaggerSpec = swaggerJsdoc(options);\nwriteFileSync('./swagger.json', JSON.stringify(swaggerSpec, null, 2));\nconsole.log('Swagger documentation generated.');` },
        { type: 'code', title: 'package.json script + regenerate', lang: 'bash', code: `# "swagger": "node swagger.js"\nnpm run swagger   # regenerates swagger.json — commit the result!` },
        { type: 'h', text: 'OpenAPI comments' },
        { type: 'p', text: 'OpenAPI comments are special documentation blocks that swagger-jsdoc reads when it generates swagger.json. They do not change how your route works — they describe the route so Swagger UI can show the method, path, parameters, request body, possible responses, and status codes. Indentation matters because the content is YAML. The course uses the @openapi marker consistently (the older @swagger marker also works).' },
        { type: 'code', title: 'documenting GET /books/{id}', lang: 'js', code: `/**\n * @openapi\n * /books/{id}:\n *   get:\n *     summary: Get one book by id\n *     tags:\n *       - Books\n *     parameters:\n *       - in: path\n *         name: id\n *         required: true\n *         description: The custom book id, such as b1\n *         schema:\n *           type: string\n *     responses:\n *       200:\n *         description: Book returned successfully\n *       404:\n *         description: Book not found\n *       500:\n *         description: Unable to retrieve book\n */\nrouter.get('/books/:id', getBookByIdHandler);` },
        { type: 'code', title: 'documenting a POST body', lang: 'js', code: `/**\n * @openapi\n * /products:\n *   post:\n *     summary: Create a product\n *     tags:\n *       - Products\n *     requestBody:\n *       required: true\n *       content:\n *         application/json:\n *           schema:\n *             type: object\n *             required: [id, name, price]\n *             properties:\n *               id:    { type: string }\n *               name:  { type: string }\n *               price: { type: number }\n *           example:\n *             id: p4\n *             name: Trail Backpack\n *             price: 79.99\n *     responses:\n *       201: { description: Product created successfully }\n *       400: { description: Invalid product data }\n */\nrouter.post('/products', createProductHandler);` },
        { type: 'h', text: 'Serve Swagger UI from Express' },
        { type: 'code', title: 'app.js', lang: 'js', code: `import swaggerUi from 'swagger-ui-express';\nimport swaggerDocument from './swagger.json' with { type: 'json' };\n\napp.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));` },
        { type: 'callout', variant: 'tip', title: 'AI drafts, you verify', body: 'Writing OpenAPI comments is a task AI does well. Let AI draft the comments, then carefully review: /books/:id must become /books/{id}, status codes must match controller behavior, and comments must sit directly above the correct route definitions.' },
        { type: 'h', text: 'Troubleshooting Swagger' },
        { type: 'list', style: 'cross', items: [
          '/api-docs does not load → confirm swagger-ui-express is installed and imported correctly.',
          'swagger-jsdoc will not install → update Node.js to the current LTS version and retry.',
          'Render cannot find swagger.json → confirm the file was generated and committed.',
          'A route is missing → confirm the route file is included in the apis list in swagger.js, then run npm run swagger again.',
          'YAML error → check the spacing in your OpenAPI comments; indentation must be consistent.',
          'Swagger accepts fields your API does not use → update the docs or the code so they match.',
        ]},
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Why is swagger-jsdoc a dev dependency?', a: 'It is only needed to generate swagger.json. The deployed app serves the generated file with swagger-ui-express, so the generator is not needed in production.' },
          { q: 'Do OpenAPI comments change how a route works?', a: 'No. They only describe the route so Swagger UI can display and test it. The comments must match the real behavior of the controller.' },
          { q: 'What must you do after changing routes?', a: 'Run npm run swagger to regenerate swagger.json and commit the file so the deployed app serves up-to-date docs.' },
        ]},
        { type: 'takeaways', items: [
          'Swagger UI at /api-docs is both documentation and an interactive test console.',
          '@openapi comments above routes generate swagger.json via npm run swagger.',
          'Document error bodies too, not just descriptions — clients need to know the 404 shape.',
          'Regenerate and commit swagger.json whenever routes change.',
        ]},
        { type: 'exercise', title: 'Mini-project: document the Books API', level: 'Core', steps: [
          'Install swagger-ui-express and swagger-jsdoc in your Week 01 project.',
          'Create swagger.js, add the swagger npm script, and generate swagger.json.',
          'Add @openapi comments for GET /books and GET /books/:id (tags, path params, 200/404/500 responses).',
          'Serve the UI at /api-docs, then test both routes with Try it out → Execute.',
          'Commit swagger.json, push, and verify the deployed /api-docs page works on Render.',
        ]},
      ],
    },
    {
      id: 'books-and-authors-project',
      title: 'Guided Project: Books & Authors API',
      minutes: 60,
      blocks: [
        { type: 'lead', text: 'Time to put Week 02 together: extend the Books API with full CRUD, add an authors collection, model the relationship, and document and test every route with Swagger — using the professional spec → issues → PR workflow.' },
        { type: 'h', text: 'The features' },
        { type: 'list', style: 'steps', items: [
          'Update the book data model to reference an authorId instead of an author name, and add the remaining CRUD operations for books (create, update, delete).',
          'Add an authors collection storing id, name, and birthYear, with all CRUD operations.',
          'Document every book and author route in Swagger so each can be tested from the browser.',
        ]},
        { type: 'h', text: 'Data models' },
        { type: 'code', title: 'book document', lang: 'json', code: `{\n  "id": "b1",\n  "authorId": "a1",\n  "title": "Pride and Prejudice",\n  "publicationDate": "1813-01-28"\n}` },
        { type: 'code', title: 'author document', lang: 'json', code: `{\n  "id": "a1",\n  "name": "Jane Austen",\n  "birthYear": 1775\n}` },
        { type: 'callout', variant: 'info', title: 'Reference, not copy', body: 'The book stores the author\'s id — not the whole author document and not just the author\'s name. This keeps the relationship clear: books.authorId points to authors.id.' },
        { type: 'h', text: 'The route contract' },
        { type: 'table', title: 'Books routes', headers: ['Route', 'Success', 'Errors'], rows: [
          ['GET /books', '200, array of books', '500'],
          ['GET /books/:id', '200, one book', '404 no match · 500'],
          ['POST /books', '201, created book', '400 missing field · 400 duplicate id · 400 unknown authorId · 500'],
          ['PUT /books/:id', '200, updated book', '400 missing field · 400 unknown authorId · 404 no match · 500'],
          ['DELETE /books/:id', '204, no body', '404 no match · 500'],
        ]},
        { type: 'table', title: 'Authors routes', headers: ['Route', 'Success', 'Errors'], rows: [
          ['GET /authors', '200, array of authors', '500'],
          ['GET /authors/:id', '200, one author', '404 no match · 500'],
          ['POST /authors', '201, created author', '400 missing field · 400 duplicate id · 500'],
          ['PUT /authors/:id', '200, updated author', '400 missing field · 404 no match · 500'],
          ['DELETE /authors/:id', '204, no body', '404 no match · 409 author still has books · 500'],
        ]},
        { type: 'h', text: 'Build order matters' },
        { type: 'callout', variant: 'tip', title: 'Authors first', body: 'Books store an authorId that points to an author document, so you should create and test the author API before finishing the book API. The book create/update validation needs real author records to check against.' },
        { type: 'code', title: 'authors model (src/models/authors.js)', lang: 'js', code: `import { getDb } from '../db/connect.js';\n\nconst getAllAuthors = async () => {\n  const db = getDb();\n  return db.collection('authors').find({}).toArray();\n};\n\nconst getAuthorById = async (id) => {\n  const db = getDb();\n  return db.collection('authors').findOne({ id });\n};\n\nconst createAuthor = async (author) => {\n  const db = getDb();\n  await db.collection('authors').insertOne(author);\n  return author;\n};\n\nconst updateAuthor = async (id, author) => {\n  const db = getDb();\n  await db.collection('authors').updateOne({ id }, { $set: author });\n  return { id, ...author };\n};\n\nconst deleteAuthor = async (id) => {\n  const db = getDb();\n  return db.collection('authors').deleteOne({ id });\n};\n\nconst authorHasBooks = async (id) => {\n  const db = getDb();\n  const count = await db.collection('books').countDocuments({ authorId: id });\n  return count > 0;\n};\n\nexport { getAllAuthors, getAuthorById, createAuthor, updateAuthor, deleteAuthor, authorHasBooks };` },
        { type: 'code', title: 'deleteAuthor controller — block when books exist', lang: 'js', code: `const deleteAuthor = async (req, res) => {\n  try {\n    const { id } = req.params;\n    const existingAuthor = await getAuthorByIdFromDb(id);\n    if (!existingAuthor) {\n      return res.status(404).json({ message: 'Author not found.' });\n    }\n    if (await authorHasBooks(id)) {\n      return res.status(409).json({ message: 'Author cannot be deleted because they still have books.' });\n    }\n    await deleteAuthorFromDb(id);\n    return res.status(204).send();\n  } catch (error) {\n    return res.status(500).json({ message: 'Unable to delete author.' });\n  }\n};` },
        { type: 'callout', variant: 'warn', title: 'AI can help — you are responsible', body: 'This is a good place to use AI to generate draft code. Then review every line: does it follow your spec, match the project patterns, and honor the coding standards? Detailed prompts produce better code — include your route behavior, required fields, status codes, and error cases.' },
        { type: 'h', text: 'The workflow, end to end' },
        { type: 'list', style: 'steps', items: [
          'Write a detailed spec for both features (data models, routes, status codes, relationship rules).',
          'Create two GitHub issues, each with a Test Plan.',
          'Branch implement-author-api: model, controllers, routes, Swagger comments, test all five routes at /api-docs, lint, PR with Closes #N, merge.',
          'Branch update-book-api: add authorId to seed data, validate authorId on create/update, add POST/PUT/DELETE, document, test, PR, merge.',
          'Verify the deployed /api-docs on Render tests every book and author route.',
          'Reflect: cite your spec, issues, PRs, Swagger pages, and deployed app.',
        ]},
        { type: 'takeaways', items: [
          'Extend a working API instead of rewriting it: authors first, then books referencing authors.',
          'authorId validation rejects unknown authors with 400; deleting an author with books returns 409.',
          'Every route gets Swagger docs and a Test Plan verified at /api-docs, locally and deployed.',
          'The PR description links the issue, summarizes changes, and pastes the verified test plan.',
        ]},
        { type: 'exercise', title: 'Capstone checkpoint', level: 'Stretch', steps: [
          'Complete both GitHub issues with specs and Test Plans.',
          'Implement the full authors API, then the full books API, each on its own branch and PR.',
          'Demonstrate in Swagger: create an author, create a book referencing them, try deleting the author (expect 409).',
          'Record a 3-minute walkthrough video showing the deployed Swagger docs, one book write route, and one controller handling 200/404/500.',
        ]},
      ],
    },
  ],
  quiz: [
    { q: 'Which pair maps POST correctly?', options: ['POST → findOne', 'POST → insertOne', 'POST → updateOne', 'POST → deleteOne'], answer: 1, explain: 'Create operations map to insertOne in MongoDB.' },
    { q: 'updateOne returns matchedCount: 0. What should the API return?', options: ['200', '201', '404', '500'], answer: 2, explain: 'matchedCount 0 means no document matched the filter — the resource was not found.' },
    { q: 'Why use the $set operator in updates?', options: ['It encrypts the document', 'It updates only the specified fields instead of replacing the whole document', 'It speeds up the query', 'It validates required fields'], answer: 1, explain: 'Without $set you can accidentally replace more of the document than intended.' },
    { q: 'A client creates a product with categoryId "c9", but no such category exists. Best response?', options: ['201 and create it anyway', '400 Bad Request', '500 Internal Server Error', '302 Redirect'], answer: 1, explain: 'The request data is invalid because the relationship points to nothing — a client error.' },
    { q: 'References in MongoDB…', options: ['Automatically join related documents', 'Store an id; you need a second query or $lookup to get related data', 'Require foreign keys', 'Only work with ObjectId'], answer: 1, explain: 'MongoDB stores the reference value but does not auto-join.' },
    { q: 'Which package serves the interactive documentation page?', options: ['swagger-jsdoc', 'swagger-ui-express', 'nodemon', 'mongodb'], answer: 1, explain: 'swagger-ui-express serves Swagger UI; swagger-jsdoc only generates swagger.json during development.' },
    { q: 'After editing OpenAPI comments, what must you do?', options: ['Restart MongoDB', 'Run npm run swagger and commit swagger.json', 'Delete node_modules', 'Nothing — it updates live'], answer: 1, explain: 'swagger.json must be regenerated and committed so local and deployed docs stay accurate.' },
    { q: 'Deleting an author who still has books should return…', options: ['204', '400', '409 Conflict', '200'], answer: 2, explain: 'Blocking the delete with 409 protects related documents from dangling references.' },
  ],
};
