import type { Module } from '../types';

export const week05: Module = {
  id: 'w5',
  week: 'Week 05',
  title: 'Pagination & Scaling List Endpoints',
  tagline: 'Keep list endpoints fast and usable as data grows: query parameters, validation, metadata, and testing.',
  level: 'Intermediate',
  hue: 150,
  related: ['w2', 'w4', 'w6'],
  sections: [
    {
      id: 'pagination',
      title: 'Pagination: Design, Validate, Test',
      minutes: 40,
      blocks: [
        { type: 'lead', text: 'Pagination limits how much data an API returns in one response. Without it, a list endpoint becomes slow, expensive, and hard to use as the database grows — GET /api/products works fine with 10 products, but not with ten thousand.' },
        { type: 'h', text: 'When to use pagination' },
        { type: 'p', text: 'Any endpoint that returns a list of records should be considered for pagination. Some lists are small today but grow over time: product catalogs, customer orders, inventory records, administrative data. Returning every record every time means slower responses, more bandwidth, and a client forced to process data it may not need.' },
        { type: 'callout', variant: 'info', title: 'Pagination is an API design decision', body: 'Pagination is not only a database technique — it is part of the API contract. Clients need to know which query parameters are supported, what the defaults are, what limits are allowed, and how to tell whether more results exist.' },
        { type: 'h', text: 'Common query parameters' },
        { type: 'list', style: 'plain', items: [
          'page — which page of results to return.',
          'limit — how many records to return per page.',
          'sort — which field controls ordering.',
          'order — ascending (lowest to highest) or descending.',
        ]},
        { type: 'code', title: 'a paginated request', lang: 'http', code: `GET /api/products?page=2&limit=10&sort=name&order=asc` },
        { type: 'p', text: 'This asks for the second page of products, 10 per page, sorted alphabetically by name.' },
        { type: 'h', text: 'Defaults and limits' },
        { type: 'list', style: 'check', items: [
          'Default page: 1',
          'Default limit: 10',
          'Maximum limit: 50',
          'Default sort: createdAt or name, depending on the endpoint',
          'Keep defaults consistent across related endpoints unless there is a clear reason to differ.',
        ]},
        { type: 'callout', variant: 'warn', title: 'Always set a maximum limit', body: 'Do not let clients request unlimited results. A maximum limit protects the API and the database from accidental or abusive requests.' },
        { type: 'h', text: 'Validate pagination parameters' },
        { type: 'p', text: 'Query parameters arrive as strings, so parse and validate them before using them in a database query. Invalid values should receive a clear 400 response.' },
        { type: 'code', title: 'invalid examples', lang: 'http', code: `GET /api/products?page=abc\nGET /api/products?page=0\nGET /api/products?limit=-5\nGET /api/products?limit=100000\nGET /api/products?sort=password` },
        { type: 'code', title: 'a helpful error response', lang: 'json', code: `{\n  "errors": [\n    {\n      "field": "limit",\n      "message": "limit must be a number between 1 and 50."\n    }\n  ]\n}` },
        { type: 'h', text: 'Response metadata' },
        { type: 'p', text: 'A paginated response should include both the data and enough metadata for the client to know which page it received and how to request the next one.' },
        { type: 'code', title: 'paginated response shape', lang: 'json', code: `{\n  "data": [],\n  "pagination": {\n    "page": 2,\n    "limit": 10,\n    "totalItems": 48,\n    "totalPages": 5,\n    "hasNextPage": true,\n    "hasPreviousPage": true\n  }\n}` },
        { type: 'code', title: 'alternative: links', lang: 'json', code: `{\n  "links": {\n    "self":     "/api/products?page=2&limit=10",\n    "next":     "/api/products?page=3&limit=10",\n    "previous": "/api/products?page=1&limit=10"\n  }\n}` },
        { type: 'h', text: 'Model: skip + limit' },
        { type: 'p', text: 'Keep database work in the model. The controller validates the request and passes trusted pagination options; the model uses skip() and limit() to request only the needed records, and countDocuments for the total.' },
        { type: 'code', title: 'src/models/products.js', lang: 'js', code: `import { Product } from './product.js';\n\nexport const getPaginatedProducts = async ({ filter = {}, page, limit, sort, order }) => {\n  const skip = (page - 1) * limit;\n  const sortOptions = { [sort]: order };\n\n  const [products, totalItems] = await Promise.all([\n    Product.find(filter).sort(sortOptions).skip(skip).limit(limit),\n    Product.countDocuments(filter)\n  ]);\n\n  return { products, totalItems };\n};` },
        { type: 'callout', variant: 'tip', title: 'The model never sees req', body: 'The model does not read req or send a response. It receives a filter and validated options and returns data — so it can later be reused by another controller or service.' },
        { type: 'h', text: 'Controller: parse, validate, respond' },
        { type: 'code', title: 'src/controllers/products.js', lang: 'js', code: `import { getPaginatedProducts } from '../models/products.js';\n\nconst allowedSortFields = ['name', 'price', 'category', 'createdAt'];\n\nconst parsePositiveInteger = (value, defaultValue) => {\n  if (value === undefined) return defaultValue;\n  const parsed = Number(value);\n  if (!Number.isInteger(parsed) || parsed < 1) return null;\n  return parsed;\n};\n\nexport const getProducts = async (req, res, next) => {\n  try {\n    const page = parsePositiveInteger(req.query.page, 1);\n    const requestedLimit = parsePositiveInteger(req.query.limit, 10);\n\n    if (!page || !requestedLimit || requestedLimit > 50) {\n      return res.status(400).json({\n        errors: [{ field: 'pagination', message: 'page and limit must be valid positive numbers. Maximum limit is 50.' }]\n      });\n    }\n\n    if (req.query.sort && !allowedSortFields.includes(req.query.sort)) {\n      return res.status(400).json({\n        errors: [{ field: 'sort', message: 'sort is not supported.' }]\n      });\n    }\n\n    const limit = requestedLimit;\n    const sort = req.query.sort || 'name';\n    const order = req.query.order === 'desc' ? -1 : 1;\n\n    const { products, totalItems } = await getPaginatedProducts({ filter: {}, page, limit, sort, order });\n\n    return res.status(200).json({\n      data: products,\n      pagination: {\n        page,\n        limit,\n        totalItems,\n        totalPages: Math.ceil(totalItems / limit),\n        hasNextPage: page * limit < totalItems,\n        hasPreviousPage: page > 1\n      }\n    });\n  } catch (error) {\n    next(error);\n  }\n};` },
        { type: 'callout', variant: 'warn', title: 'Use an allowlist for sort', body: 'An allowlist limits sorting to supported, useful fields such as name, price, or category. It keeps the API contract clear and avoids unexpected query behavior from arbitrary client-supplied field names.' },
        { type: 'h', text: 'Document pagination in Swagger' },
        { type: 'code', title: 'query parameters in OpenAPI', lang: 'js', code: `parameters:\n  - name: page\n    in: query\n    schema: { type: integer, default: 1, minimum: 1 }\n  - name: limit\n    in: query\n    schema: { type: integer, default: 10, minimum: 1, maximum: 50 }\n  - name: sort\n    in: query\n    schema: { type: string, enum: [name, price, category, createdAt] }\n  - name: order\n    in: query\n    schema: { type: string, enum: [asc, desc] }` },
        { type: 'h', text: 'Testing pagination' },
        { type: 'list', style: 'check', items: [
          'The endpoint returns only the requested number of records.',
          'The second page returns different records than the first.',
          'The response includes pagination metadata.',
          'Invalid page or limit values return 400.',
          'The maximum limit is enforced.',
          'Sorting changes the order of returned results.',
        ]},
        { type: 'demo', name: 'pagination-lab' },
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Why paginate as data grows?', a: 'Pagination limits records per response, reducing unnecessary database work, bandwidth use, and client-side processing.' },
          { q: 'What do page and limit mean?', a: 'page identifies which page of results the client wants; limit is the maximum number of records on that page.' },
          { q: 'Why enforce a maximum limit?', a: 'It prevents accidental or abusive requests for very large result sets, protecting the API and database.' },
          { q: 'What metadata helps a client build Next/Previous controls?', a: 'page, limit, totalItems, totalPages, hasNextPage, and hasPreviousPage.' },
          { q: 'Why an allowlist for sort?', a: 'It limits sorting to supported fields, keeping the contract clear and avoiding unexpected query behavior.' },
        ]},
        { type: 'takeaways', items: [
          'Paginate every list endpoint before the data grows, not after.',
          'page/limit/sort/order with documented defaults and a maximum limit.',
          'Return data plus pagination metadata so clients can build controls.',
          'Model skips and limits; controller parses and validates; Swagger documents everything.',
        ]},
        { type: 'exercise', title: 'Mini-project: paginate a list endpoint', level: 'Core', steps: [
          'Pick one list endpoint in your project and add page, limit, sort, and order parameters.',
          'Implement parsePositiveInteger-style validation with a maximum limit of 50.',
          'Update the model to use skip() and limit() plus countDocuments in a Promise.all.',
          'Return the pagination metadata object and document all parameters in Swagger.',
          'Write the six pagination tests from the checklist and run each against your deployed API.',
        ]},
      ],
    },
    {
      id: 'debugging-playbook',
      title: 'Debugging Playbook: Real Problems, Real Fixes',
      minutes: 25,
      blocks: [
        { type: 'lead', text: 'Debugging is a skill, not luck. This section collects real problems students hit across the stack — environment variables, permissions, network access, frontend/backend mismatches — and the exact fixes that solved them.' },
        { type: 'h', text: 'The loop that works' },
        { type: 'list', style: 'steps', items: [
          'Read the error carefully — the exact words matter.',
          'Check the server terminal, not just the browser.',
          'Verify the data source: database name, collection, permissions.',
          'Restart cleanly if the environment changed.',
          'Ask one precise question with the exact output.',
        ]},
        { type: 'h', text: 'Problem → cause → fix' },
        { type: 'table', headers: ['Problem', 'Cause', 'Fix'], rows: [
          ['Invalid connection string', '@ in the MongoDB password', 'URL-encode it: @ → %40'],
          ['/books returned []', 'App connected to the wrong database', 'Check .env MONGODB_DB_NAME; verify with a Node script'],
          ['Server not picking up .env changes', 'Nodemon does not watch .env', 'Restart manually; kill stuck node processes'],
          ['Render: MONGODB_URI is required', 'Variable added as a Secret File, not an Environment Variable', 'Add it as a direct environment variable'],
          ['Render: SSL/TLS alert', 'Atlas IP whitelist missing Render\'s IPs', 'Add Render\'s outbound ranges (or 0.0.0.0/0) in Atlas'],
          ['user is not allowed to do action [insert]', 'MongoDB user was read-only', 'Change role to "Read and write to any database"'],
          ['Cannot find package \'mongoose\'', 'package.json updated but deps not installed', 'npm install'],
          ['Swagger: routes missing', 'swagger.json not regenerated', 'npm run swagger + commit'],
          ['detailsEl is not defined', 'Toggle block placed outside the click handler', 'Move it inside the handler, after detailsEl is defined'],
          ['Station details overflowed container', 'CSS flex: 0 0 auto with no wrapping', 'flex: 1 1 0; min-width: 0 + flex-wrap: wrap'],
        ]},
        { type: 'callout', variant: 'tip', title: 'Pattern recognition', body: 'Most of these failures share a shape: the layer you are looking at is not the layer that is broken. The browser shows nothing because the server crashed; the server crashes because the environment variable is missing; the query returns nothing because the connection points at the wrong database. Trace the whole path before changing code.' },
        { type: 'qa', title: 'Rapid-fire diagnosis', items: [
          { q: 'Your API returns an empty array locally but Atlas shows data. First thing to check?', a: 'MONGODB_DB_NAME in .env — you may be connected to the wrong database. Verify by logging which database a Node script sees.' },
          { q: 'You edited .env but the server behaves the same. Why?', a: 'Nodemon does not watch .env files. Restart the server manually (and kill any stuck node processes).' },
          { q: 'Render deploy fails with "MONGODB_URI is required" even though you added it.', a: 'It was likely added as a Secret File rather than an Environment Variable. Add it as a direct env var in the Render dashboard.' },
        ]},
        { type: 'takeaways', items: [
          'Read the error, check the server terminal, verify the data source, restart cleanly, ask precisely.',
          'URL-encode special characters in connection strings (%40 for @).',
          'Nodemon ignores .env changes — restart manually.',
          'Atlas security has two halves: database user permissions and the IP access list.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: build your own playbook', level: 'Warm-up', steps: [
          'Pick the last three bugs you fixed in any project.',
          'For each, write the problem in one line, the root cause in one line, and the fix in one line.',
          'For each, add which step of the debugging loop would have found it fastest.',
          'Keep the list somewhere you will actually see it next time you are stuck.',
        ]},
      ],
    },
  ],
  quiz: [
    { q: 'What does GET /api/products?page=2&limit=10 request?', options: ['The first 2 products', 'Products 11–20', 'All products sorted by page', '10 pages of 2 products'], answer: 1, explain: 'Page 2 with limit 10 skips the first 10 records and returns the next 10.' },
    { q: 'Why enforce a maximum limit?', options: ['To make responses prettier', 'To protect the API and database from accidental or abusive large requests', 'Because MongoDB requires it', 'To speed up Swagger'], answer: 1, explain: 'An unlimited limit lets any client request the entire collection at once.' },
    { q: 'Which metadata tells a client a next page exists?', options: ['totalItems', 'hasNextPage', 'sort', 'status'], answer: 1, explain: 'hasNextPage (computed from page × limit vs. totalItems) drives the Next button.' },
    { q: 'Query params arrive as…', options: ['Numbers', 'Strings that must be parsed and validated', 'JSON objects', 'Booleans'], answer: 1, explain: 'req.query values are strings; parse them and reject invalid values with 400.' },
    { q: 'Where does pagination math (skip/limit) belong?', options: ['In the router', 'In the model, receiving validated options from the controller', 'In Swagger comments', 'In the browser'], answer: 1, explain: 'The controller owns HTTP validation; the model owns database work.' },
    { q: 'Your .env edit has no effect under Nodemon because…', options: ['Node caches all files', 'Nodemon does not watch .env — restart manually', 'Express blocks .env', 'The PORT is wrong'], answer: 1, explain: 'Kill and restart the dev server after changing environment files.' },
    { q: 'Render reports "SSL/TLS alert" connecting to Atlas. Likely fix?', options: ['Reinstall Express', 'Add Render\'s outbound IPs to the Atlas IP access list', 'Rename the database', 'Downgrade Node'], answer: 1, explain: 'Atlas only accepts connections from whitelisted addresses; Render\'s outbound ranges must be added.' },
    { q: 'A MongoDB user "not allowed to do action [insert]" means…', options: ['The schema is invalid', 'The database user is read-only — change its role to read/write', 'The route is missing', 'The collection is full'], answer: 1, explain: 'Atlas database users have roles; inserts require a read-and-write role.' },
  ],
};
