import type { Module } from '../types';

export const week01: Module = {
  id: 'w1',
  week: 'Week 01',
  title: 'Foundations of Web Services',
  tagline: 'What a web service is, how REST works, and your first Express + MongoDB API deployed to the cloud.',
  level: 'Beginner',
  hue: 233,
  related: ['w2', 'w3', 'w5'],
  sections: [
    {
      id: 'web-services-and-apis',
      title: 'Web Services & APIs',
      minutes: 25,
      blocks: [
        { type: 'lead', text: 'A web service is software that receives network requests and returns responses. Most modern web services use HTTP and send data as JSON. This section builds the mental model everything else in the course depends on.' },
        { type: 'h', text: 'What exactly is a web service?' },
        { type: 'p', text: 'A web service is a running program that listens for requests over a network and sends back responses. When your browser, a mobile app, or even another server needs data, it sends an HTTP request to the web service. The service does the work — reading a database, checking rules, computing a result — and returns a response, usually formatted as JSON.' },
        { type: 'p', text: 'An API (Application Programming Interface) is the contract that explains how a client should use that service. The contract includes routes, methods, expected input, response shapes, and error behavior. In simple terms: the API defines the rules, and the web service is the running code that follows those rules.' },
        { type: 'callout', variant: 'realworld', title: 'The restaurant analogy', body: 'Think of an API like a menu in a restaurant. The menu tells you what you can request. The kitchen is like the web service — it takes your request, does the work, and sends back a result. Diners never walk into the kitchen; clients never touch your database. Everything goes through the menu.' },
        { type: 'p', text: 'When a service has a clear API, different developers can use it without guessing. This matters in real jobs because teams are often split across frontend and backend. A clear API lets both sides work in parallel: the backend team builds the service, the frontend team builds against the documented contract.' },
        { type: 'h', text: 'REST: design ideas for predictable APIs' },
        { type: 'p', text: 'Many web services are designed as REST APIs. REST stands for Representational State Transfer. In practice, REST is a set of design ideas for using HTTP in a consistent way that is focused on resources.' },
        { type: 'p', text: 'A resource is a thing your API works with, such as movies, users, orders, or reviews. REST-style APIs represent resources with clear URLs and use HTTP methods to describe the action being requested. A client should be able to look at a method and a URL and have a good idea of what the route does.' },
        { type: 'table', title: 'REST routes for a "movies" resource', headers: ['Request', 'Meaning'], rows: [
          ['GET /movies', 'Retrieve a list of movie resources'],
          ['GET /movies/m1', 'Retrieve one movie resource'],
          ['POST /movies', 'Create a new movie resource'],
          ['PUT /movies/m1 (or PATCH)', 'Update an existing movie resource'],
          ['DELETE /movies/m1', 'Remove a movie resource'],
        ]},
        { type: 'h', text: 'Server-side rendering vs. web services' },
        { type: 'p', text: 'In a server-side rendering approach, the backend builds HTML on the server and sends that HTML to the browser. The browser mostly just displays what the server sends.' },
        { type: 'p', text: 'In a web services approach, the backend usually sends data only. A separate client decides how to display that data. Separating data from presentation creates a clean separation of responsibilities — and makes it possible for a mobile app, a website, and a Python data-science script to all use the same web service.' },
        { type: 'table', headers: ['Server-side rendering', 'Web services'], rows: [
          ['Server returns ready-to-display HTML.', 'Server returns data, often JSON.'],
          ['Response is designed for direct browser viewing.', 'Response is designed for programmatic use by many kinds of clients.'],
        ]},
        { type: 'code', title: 'server-rendered response (HTML)', lang: 'html', code: `<html>\n  <body>\n    <h1>Movies</h1>\n    <ul>\n      <li>Hidden Harbor</li>\n      <li>Mountain Signal</li>\n    </ul>\n  </body>\n</html>` },
        { type: 'code', title: 'web service response (JSON)', lang: 'json', code: `[\n  {\n    "id": "m1",\n    "director": "Ava Morgan",\n    "title": "Hidden Harbor",\n    "releaseYear": 2021\n  },\n  {\n    "id": "m2",\n    "director": "Noah Chen",\n    "title": "Mountain Signal",\n    "releaseYear": 2019\n  }\n]` },
        { type: 'callout', variant: 'info', title: 'What about XML?', body: 'Web services can also return XML. XML was used heavily in earlier web service systems and still exists in some older or specialized APIs. Today, most modern web APIs use JSON because it is smaller, easier to read, and works naturally with JavaScript.' },
        { type: 'h', text: 'How clients and services interact' },
        { type: 'p', text: 'A request starts when a client sends a URL and method, such as GET /movies. The server finds matching route code and runs it. That code may read from a database, do checks, and prepare a response. The response always includes a status code, and often includes JSON data. The status code tells the client whether the request worked; the JSON gives the actual data or error message.' },
        { type: 'diagram', name: 'request-flow', caption: 'Client-side JavaScript requests data from a web service, then renders the response in the browser.' },
        { type: 'code', title: 'a raw HTTP request packet', lang: 'http', code: `GET /movies HTTP/1.1\nHost: api.example.com\nAccept: application/json\nUser-Agent: Browser JavaScript` },
        { type: 'code', title: 'a matching response packet', lang: 'http', code: `HTTP/1.1 200 OK\nContent-Type: application/json\n\n[{ "id": "m1", "title": "Hidden Harbor", "releaseYear": 2021 }]` },
        { type: 'h', text: 'Common HTTP status codes in APIs' },
        { type: 'list', style: 'plain', items: [
          '200 OK — the request succeeded and data is returned.',
          '201 Created — a new resource was created successfully.',
          '400 Bad Request — request input is invalid.',
          '404 Not Found — the requested resource does not exist.',
          '500 Internal Server Error — something unexpected failed on the server.',
        ]},
        { type: 'demo', name: 'status-explorer' },
        { type: 'h', text: 'Core design ideas in API work' },
        { type: 'list', style: 'check', items: [
          'Consistency — similar routes should behave in similar ways, so client code can handle errors one common way.',
          'Clarity — request and response formats should be easy to understand; clear rules reduce mistakes.',
          'Predictability — status codes and error messages should follow stable patterns.',
          'Separation of concerns — the API returns data; clients decide how to present it. One API can serve a website, a phone app, and another backend service without rewriting business logic.',
        ]},
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'What is the difference between an API and a web service?', a: 'The API is the contract — the rules describing routes, methods, inputs, outputs, and errors. The web service is the running code that follows those rules and actually responds to requests.' },
          { q: 'Why do modern web APIs prefer JSON over XML?', a: 'JSON is smaller, easier to read, and maps naturally to JavaScript objects, which makes it the default choice for modern web services.' },
          { q: 'What two parts of a response does a client read?', a: 'The status code (did the request work?) and the body (the actual JSON data or error message).' },
        ]},
        { type: 'takeaways', items: [
          'A web service receives HTTP requests and returns responses, usually JSON.',
          'The API is the contract; the web service is the running code that honors it.',
          'REST organizes APIs around resources plus HTTP methods, making routes predictable.',
          'Web services return data, not finished HTML — one backend can power many clients.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: design three routes', level: 'Warm-up', steps: [
          'Pick a resource from daily life (e.g., playlists, recipes, gym workouts).',
          'Write the five REST routes for it (list, get one, create, update, delete) using the movies table as your pattern.',
          'For each route, write which status code you would return on success and on failure.',
          'Swap with a classmate: can they predict what each of your routes does just from the method and URL?',
        ]},
      ],
    },
    {
      id: 'express-project-setup',
      title: 'Project Setup: Express, npm & Environment Variables',
      minutes: 35,
      blocks: [
        { type: 'lead', text: 'In this hands-on section you create a GitHub repository, initialize a Node.js application, install Express and Nodemon, and wire up environment variables — the exact setup used by professional teams.' },
        { type: 'h', text: 'Create and clone a GitHub repo' },
        { type: 'list', style: 'steps', items: [
          'In a browser, navigate to GitHub and sign in.',
          'Create a new public repository for the books API project, e.g. cse341-books.',
          'Do not start from a template, add a README, or add a license.',
          'Under "Add .gitignore", select Node.',
          'Create the repository, then clone it to your computer and open the folder in VS Code.',
        ]},
        { type: 'h', text: 'Initialize the Node.js application' },
        { type: 'list', style: 'steps', items: [
          'Run npm init in the project root. Accept defaults, but set entry point to server.js (not index.js) and type to module (not commonjs).',
          'Run npm install express to install the Express.js framework.',
          'Run npm install --save-dev nodemon to install Nodemon as a development dependency.',
          'Open package.json and add start and dev scripts that load the .env file.',
        ]},
        { type: 'code', title: 'package.json', lang: 'json', code: `{\n  "name": "cse341-books",\n  "version": "1.0.0",\n  "type": "module",\n  "main": "server.js",\n  "scripts": {\n    "start": "node --env-file=.env server.js",\n    "dev": "nodemon --env-file=.env server.js",\n    "test": "echo \\"Error: no test specified\\" && exit 1"\n  },\n  "dependencies": {\n    "express": "^5.2.1"\n  },\n  "devDependencies": {\n    "nodemon": "^3.1.14"\n  }\n}` },
        { type: 'h', text: 'Set up environment variables' },
        { type: 'p', text: 'To keep configuration flexible, use environment variables for settings such as the port number and database connection string. Create a .env file in the project root, add PORT=3000, and verify that .env is listed in .gitignore so you never commit it.' },
        { type: 'callout', variant: 'danger', title: 'Never commit your .env file', body: 'Environment files often contain private configuration values such as database connection strings, usernames, passwords, and API keys. If a .env file is pushed to GitHub, those secrets may be exposed to anyone who can access the repository — and they remain visible in the Git history even after the file is deleted. Keep .env in .gitignore and store production values in the hosting service\'s environment variable settings instead.' },
        { type: 'h', text: 'Implement a basic Express app and server' },
        { type: 'p', text: 'Keep the Express app in one file (app.js) and the server startup in another (server.js). This makes the app easier to test later, because tests can import the app without starting a real server port.' },
        { type: 'code', title: 'app.js — Express configuration', lang: 'js', code: `import express from 'express';\n\nconst app = express();\n\napp.use(express.json());\n\napp.get('/', (req, res) => {\n  return res.status(200).json({ message: 'Server is running' });\n});\n\nexport default app;` },
        { type: 'code', title: 'server.js — startup', lang: 'js', code: `import app from './app.js';\n\nconst PORT = process.env.PORT;\n\nif (!PORT) {\n  throw new Error('PORT is not defined. Make sure your local npm scripts reference the .env file with --env-file=.env, or define PORT in your hosted environment settings.');\n}\n\napp.listen(PORT, () => {\n  console.log(\`Server listening at 127.0.0.1:\${PORT}\`);\n});` },
        { type: 'callout', variant: 'tip', title: 'Fail fast on missing configuration', body: 'Throwing an error when PORT is missing means you know immediately if the .env file is not being read. Failing clearly at startup is far better than letting the app run with missing configuration.' },
        { type: 'list', style: 'check', items: [
          'Start the app with npm run dev.',
          'Navigate to http://127.0.0.1:3000 in your browser.',
          'Verify it responds with JSON: { "message": "Server is running" }.',
        ]},
        { type: 'takeaways', items: [
          'npm init with entry point server.js and type: module sets up modern ESM Node.',
          'The --env-file=.env flag loads environment variables without extra packages.',
          'Split app.js (Express config) from server.js (startup) for testability.',
          'Secrets live in .env locally and in the host\'s env settings in production — never in Git.',
        ]},
        { type: 'exercise', title: 'Mini-project: your first JSON API', level: 'Core', steps: [
          'Complete the full setup above in a fresh repository.',
          'Add a second route, GET /health, that returns { "status": "ok" } with status 200.',
          'Change PORT to 4000 in .env, restart, and confirm the app responds on the new port.',
          'Remove PORT from .env temporarily and observe the startup error — then restore it.',
        ]},
      ],
    },
    {
      id: 'coding-standards-eslint',
      title: 'Coding Standards & ESLint',
      minutes: 30,
      blocks: [
        { type: 'lead', text: 'Coding standards are shared rules about how code should be written. They help a team produce code that is easier to read, review, test, and maintain — and ESLint enforces them automatically.' },
        { type: 'h', text: 'Why coding standards matter' },
        { type: 'p', text: 'When code follows consistent standards, you spend less time decoding style differences and more time thinking about logic. Standards also reduce bugs: some patterns are not just style choices — they help avoid outdated syntax, inconsistent error handling, or code that behaves in surprising ways.' },
        { type: 'p', text: 'Most software companies have coding standards developers must follow. Google publishes style guides for TypeScript and Python; Microsoft publishes coding guidelines for TypeScript and VS Code. Standards are how teams write code that stays consistent across many projects.' },
        { type: 'callout', variant: 'warn', title: 'AI-generated code still needs review', body: 'AI-generated code may be functional, but it may not match the standards of your course or team. You still need to review it, lint it, and change it so it matches your project\'s rules.' },
        { type: 'h', text: 'The course coding standards' },
        { type: 'table', headers: ['Standard', 'Why'], rows: [
          ['Use ESM syntax: import and export.', 'ESM is the modern JavaScript module system used by current Node.js projects.'],
          ['Do not use CommonJS: require or module.exports.', 'Mixing module systems causes confusion and makes project structure less predictable.'],
          ['Use arrow functions and explicit return where needed.', 'Arrow functions provide consistent modern syntax and avoid confusion around this.'],
          ['Use async/await with try/catch instead of .then()/.catch().', 'Asynchronous server code is easier to read and debug than chained promise handlers.'],
          ['const by default; let only when reassigned; never var.', 'Makes it clear when values are not meant to be reassigned.'],
          ['Return after sending an Express response.', 'Prevents later code in the same handler from continuing after a response was sent.'],
          ['Keep route handlers focused; move DB logic to models.', 'Small handlers are easier to test, review, and reuse.'],
          ['Use consistent JSON error shapes, e.g. { "message": "Book not found" }.', 'Predictable responses make client code easier to write and debug.'],
          ['Do not show full error details to API clients.', 'Clients need safe messages, not stack traces or internal database details.'],
          ['Use descriptive names: requestedId, book, database.', 'Clear names reduce confusion when several records or collections are involved.'],
          ['Validate required environment variables at startup.', 'Failing clearly at startup beats running with missing configuration.'],
        ]},
        { type: 'h', text: 'How ESLint helps' },
        { type: 'p', text: 'ESLint is a tool that checks your code for rule violations. It can warn you about patterns that do not match your standards and can sometimes fix simpler issues automatically. ESLint does not replace thinking — it is a guardrail that catches many mistakes quickly.' },
        { type: 'code', title: 'terminal', lang: 'bash', code: `npm install --save-dev eslint\n\n# package.json scripts:\n#   "lint": "eslint ."\n#   "lint:fix": "eslint . --fix"\n\nnpm run lint       # check for violations\nnpm run lint:fix   # auto-fix what can be fixed` },
        { type: 'code', title: 'eslint.config.js (course configuration)', lang: 'js', code: `export default [\n  {\n    ignores: ['node_modules/**']\n  },\n  {\n    files: ['**/*.js'],\n    languageOptions: {\n      ecmaVersion: 'latest',\n      sourceType: 'module',\n      globals: {\n        console: 'readonly',\n        process: 'readonly'\n      }\n    },\n    rules: {\n      'prefer-arrow-callback': 'error',\n      'no-var': 'error',\n      'prefer-const': 'error',\n      'arrow-body-style': ['error', 'always'],\n      'consistent-return': 'error',\n      'no-restricted-syntax': [\n        'error',\n        { selector: "CallExpression[callee.name='require']", message: 'Use ESM import syntax instead of require().' },\n        { selector: "CallExpression[callee.property.name='then']", message: 'Use async/await instead of .then().' },\n        { selector: "ExpressionStatement > CallExpression[callee.object.name='res'][callee.property.name=/^(json|send)$/]", message: 'Return Express responses, such as return res.status(200).json(data).' }\n      ]\n    }\n  }\n];` },
        { type: 'h', text: 'Integrate linting into your workflow' },
        { type: 'list', style: 'steps', items: [
          'Run npm run lint after you finish a small piece of work — do not wait until the end of the assignment.',
          'Some problems are safe to fix automatically: run npm run lint:fix.',
          'Run npm run lint again to confirm remaining issues are resolved.',
          'Before every commit or pull request, make sure the lint check passes.',
          'Never merge or submit code that still has unresolved lint errors.',
        ]},
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Which lint problems auto-fix, and which need manual work?', a: 'Mechanical changes like var → const can be auto-fixed by eslint --fix. Behavioral issues like a missing return before an Express response require you to fix them by hand.' },
          { q: 'Does ESLint replace code review?', a: 'No. ESLint is a guardrail that catches rule violations quickly, but you still need to review code for correctness and clarity. Not every quality issue can be checked automatically.' },
        ]},
        { type: 'takeaways', items: [
          'Standards make code easier to read, review, test, and maintain — for teammates and your future self.',
          'ESLint enforces standards automatically; npm run lint and npm run lint:fix are part of your normal workflow.',
          'Some issues auto-fix; others (like a missing return) need manual fixes.',
          'Lint AI-generated code immediately, then review it yourself.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: break it and fix it', level: 'Warm-up', steps: [
          'Temporarily change const PORT to var PORT in server.js.',
          'Temporarily remove the return before res.status(200).json(...) in app.js.',
          'Run npm run lint and note both errors.',
          'Run npm run lint:fix — observe var becomes const, but the missing return remains.',
          'Fix the return by hand and confirm npm run lint passes clean.',
        ]},
      ],
    },
    {
      id: 'nosql-mongodb',
      title: 'NoSQL Databases & MongoDB',
      minutes: 40,
      blocks: [
        { type: 'lead', text: 'A NoSQL database stores data differently from traditional tables. MongoDB stores data as documents that look very similar to JSON — which is exactly why it fits JavaScript web services so naturally.' },
        { type: 'h', text: 'Documents and collections' },
        { type: 'p', text: 'In MongoDB, a document is one stored record. A document uses key-value pairs, similar to a JavaScript object. A collection is a group of related documents — similar to a table in a relational database, but the documents inside it do not need to match perfectly.' },
        { type: 'code', title: 'one document in the "trails" collection', lang: 'json', code: `{\n  "_id": { "$oid": "69d80cf8e27c83a1a75818a0" },\n  "name": "Pine Ridge Trail",\n  "lengthKm": 10.3,\n  "difficulty": "moderate",\n  "openSeason": "summer"\n}` },
        { type: 'p', text: 'Each MongoDB document has an _id field — the unique identifier for that document. MongoDB creates it automatically if you do not provide one. In many projects this value is an ObjectId: a 12-byte value usually represented as a 24-character hexadecimal string. It helps MongoDB find one specific document quickly.' },
        { type: 'table', title: 'Relational database vs. MongoDB', headers: ['Relational Database', 'MongoDB'], rows: [
          ['Data is stored in tables with rows.', 'Data is stored in collections with documents.'],
          ['Rows in one table follow the same column structure.', 'Documents in one collection can have slightly different fields.'],
          ['Related data is usually stored in separate tables and joined.', 'Related data may be stored in separate collections or nested in one document.'],
        ]},
        { type: 'h', text: 'Querying MongoDB' },
        { type: 'p', text: 'A query is a request for data. When your Express server talks to MongoDB, it sends a query to a collection and MongoDB returns matching documents. If you want all documents, the query needs no filter; if you want matching documents, you include a filter object.' },
        { type: 'code', title: 'find() for many, findOne() for one', lang: 'js', code: `// every document in the trails collection\nconst allTrails = await db.collection('trails').find().toArray();\n\n// one document whose name matches\nconst oneTrail = await db.collection('trails').findOne({ name: 'Pine Ridge Trail' });` },
        { type: 'p', text: 'In APIs it is common to request one document by id. Because MongoDB usually stores ids as ObjectId values, your route code often needs to validate the id string from the URL and convert it into an ObjectId before querying.' },
        { type: 'code', title: 'validating and converting an id', lang: 'js', code: `import { ObjectId } from 'mongodb';\n\nif (!ObjectId.isValid(req.params.id)) {\n  return res.status(400).json({ message: 'Invalid id format' });\n}\n\nconst trailId = new ObjectId(req.params.id);\nconst trail = await db.collection('trails').findOne({ _id: trailId });` },
        { type: 'callout', variant: 'tip', title: '400 vs. 404 for ids', body: 'An invalid id format is a client input problem, so it should usually return 400 Bad Request. A valid id that does not match any document should usually return 404 Not Found.' },
        { type: 'h', text: 'The request-response flow with MongoDB' },
        { type: 'list', style: 'steps', items: [
          'A client sends an HTTP request, such as GET /trails.',
          'The Express route queries the MongoDB trails collection.',
          'MongoDB returns matching documents.',
          'The route sends those documents back as JSON.',
        ]},
        { type: 'callout', variant: 'warn', title: 'Collection ≠ document', body: 'Do not confuse a collection with one document. If a route should return one item, make sure your query looks for one specific document instead of returning the whole collection.' },
        { type: 'h', text: 'Connect your app to MongoDB Atlas' },
        { type: 'p', text: 'MongoDB Atlas gives you a cloud-hosted database your Express app connects to with a connection string. Create a free M0 cluster, create a database user, and copy the Node.js connection string into a MONGODB_URI variable in your .env file.' },
        { type: 'code', title: '.env', lang: 'bash', code: `PORT=3000\nMONGODB_URI=mongodb+srv://<username>:<password>@<cluster-url>\nMONGODB_DB_NAME=practice` },
        { type: 'code', title: 'src/db/connect.js — the connection helper', lang: 'js', code: `import { MongoClient } from 'mongodb';\n\nlet database;\n\nconst connectToDb = async () => {\n  const connectionString = process.env.MONGODB_URI;\n  if (!connectionString) {\n    throw new Error('MONGODB_URI is required.');\n  }\n  const client = new MongoClient(connectionString);\n  await client.connect();\n  database = client.db(process.env.MONGODB_DB_NAME || 'practice');\n  return database;\n};\n\nconst getDb = () => {\n  if (!database) {\n    throw new Error('Database not initialized. Call connectToDb first.');\n  }\n  return database;\n};\n\nexport { connectToDb, getDb };` },
        { type: 'code', title: 'server.js — connect before listening', lang: 'js', code: `import app from './app.js';\nimport { connectToDb } from './src/db/connect.js';\n\nconst PORT = process.env.PORT;\nif (!PORT) {\n  throw new Error('PORT is not defined.');\n}\n\nconst startServer = async () => {\n  try {\n    await connectToDb();\n    app.listen(PORT, () => {\n      console.log(\`Server listening on port \${PORT}\`);\n    });\n  } catch (error) {\n    console.error('Database connection failed:', error.message);\n    process.exit(1);\n  }\n};\n\nawait startServer();` },
        { type: 'callout', variant: 'warn', title: 'IP access list problems', body: 'MongoDB Atlas only allows connections from addresses you have allowed. If you cannot connect, check that your current IP address is in the Atlas IP access list. You can add 0.0.0.0/0 to allow access from anywhere, but be aware this is a security risk — prefer your correct IP or range whenever possible.' },
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'What is a NoSQL database?', a: 'A database that stores data in a format different from the traditional table model. In MongoDB, that format is documents grouped into collections.' },
          { q: 'What is the difference between a document and a collection?', a: 'A document is one stored record; a collection is a group of related documents.' },
          { q: 'What does the _id field do?', a: 'It uniquely identifies one document, helping MongoDB find a specific record quickly.' },
          { q: 'Why convert a route value into an ObjectId before querying?', a: 'Many document ids are stored as ObjectId values, not plain strings. Converting the route value helps the query match the document correctly.' },
          { q: 'How do you query for all documents in a collection?', a: 'Call find() on the collection and convert the results to an array with toArray().' },
        ]},
        { type: 'takeaways', items: [
          'Document = one record; collection = a group of documents.',
          '_id is created automatically; ObjectId is the default type (24 hex characters).',
          'find() + toArray() returns many; findOne(filter) returns one.',
          'Connect at startup with connectToDb(), then use getDb() everywhere else.',
          'Invalid id format → 400; valid id with no match → 404.',
        ]},
        { type: 'exercise', title: 'Mini-project: practice the connection', level: 'Core', steps: [
          'Create a free MongoDB Atlas M0 cluster named books-cluster (AWS, same region as your hosting).',
          'Create a practice database with a trails collection and insert at least 3 trail documents.',
          'Add the connect.js helper to your app and update server.js to connect before listening.',
          'Add a temporary GET /trails route using find({}).toArray() and verify it returns your documents.',
          'Once verified, remove the practice route — keep src/db/connect.js for the assignment.',
        ]},
      ],
    },
    {
      id: 'deployment-render',
      title: 'Deployment with Render',
      minutes: 20,
      blocks: [
        { type: 'lead', text: 'A web service only becomes useful when other people can reach it. In this section you deploy your Express app to Render, a cloud host connected directly to your GitHub repository.' },
        { type: 'h', text: 'Create the Render web service' },
        { type: 'list', style: 'steps', items: [
          'Navigate to Render.com and sign in with your GitHub account.',
          'On the dashboard, create a new Web Service and authorize Render to access your repositories.',
          'Select the repository for your books API project.',
          'Choose a region close to your location.',
          'Set the Build command to npm install and the Start command to node server.js.',
          'Select the Free instance type and deploy.',
        ]},
        { type: 'h', text: 'Environment variables in production' },
        { type: 'p', text: 'When you run the app locally it reads values from your .env file. When you deploy, there is no .env file, so you add those values in Render\'s Environment tab: MONGODB_URI and MONGODB_DB_NAME. Render makes them available through process.env, just like your local .env file does.' },
        { type: 'callout', variant: 'warn', title: 'Do not add a PORT variable', body: 'Render automatically provides a PORT environment variable to your app. If you add your own PORT variable, it might conflict with the one Render provides and cause problems.' },
        { type: 'h', text: 'Deploy and verify' },
        { type: 'list', style: 'check', items: [
          'Wait for the build logs to show a successful deploy; fix any errors before proceeding.',
          'Open the URL Render gives you — the first visit on a free service may take a moment to load.',
          'Verify the root route responds with JSON and HTTP status 200.',
          'Record the deployed URL so you can reference it later.',
        ]},
        { type: 'h', text: 'Allow Render to reach MongoDB Atlas' },
        { type: 'p', text: 'MongoDB Atlas restricts connections to trusted places. In your Render service, open Connect → Outbound IP Addresses, copy the ranges (for example 74.220.48.0/24), and add each one to the Atlas IP Access List under Database and Network Access. Wait for Atlas to finish updating before testing.' },
        { type: 'takeaways', items: [
          'Render connects to your GitHub repo and deploys on every push to main.',
          'Build command: npm install. Start command: node server.js.',
          'Production secrets go in Render environment variables, never in Git.',
          'Render provides PORT automatically; Atlas needs Render\'s outbound IPs whitelisted.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: verify the deployed API', level: 'Warm-up', steps: [
          'Open your Render URL and confirm the root route returns JSON with status 200.',
          'Run curl -i https://<your-deployed-url>/ from the terminal and read the status line and headers.',
          'Trigger a fresh deploy with Manual Deploy → From last commit and watch the build logs.',
          'Break the connection (temporarily remove the Atlas IP entry), observe the failure, then restore it.',
        ]},
      ],
    },
    {
      id: 'professional-workflow',
      title: 'The Professional Workflow: Spec → Plan → Implement → Reflect',
      minutes: 35,
      blocks: [
        { type: 'lead', text: 'Every assignment in this course follows the same four-part process that professional software engineers use: develop a detailed specification, prepare a plan, implement the plan, and reflect on the results.' },
        { type: 'h', text: 'Why this process matters' },
        { type: 'p', text: 'Many beginners start coding right away without thinking about how their work fits the larger design. This leads to extra work and hidden bugs. A short planning process improves code quality and helps you work more confidently. It also makes AI far more useful: with clear directions, an AI agent produces solutions that are complete and correct far more often.' },
        { type: 'h', text: 'Part 1 — Develop the specification' },
        { type: 'p', text: 'A detailed spec is a document that describes exactly what your API should do: the endpoints available, the methods supported, the expected input, the output returned, and the way errors are handled. A written spec helps you think before you code — many bugs happen when requirements are unclear, and a short planning step can prevent hours of rework.' },
        { type: 'list', style: 'steps', items: [
          'Understand the feature: read the description slowly and identify the key requirements.',
          'Research the feature area: REST endpoint design, JSON response structure, HTTP status codes.',
          'Draft Version 1 of the spec.',
          'Evaluate it with guided questions: bugs? security concerns? slow routes? unclear errors?',
          'Produce Version 2 with concrete JSON examples for success and error responses.',
        ]},
        { type: 'code', title: 'Version 1 of a Books API spec (excerpt)', lang: 'js', code: `# Books API Spec\n## Purpose\nCreate a basic web service that returns book data.\n\n## Data Model\nBook fields:\n- id: string\n- author: string\n- title: string\n- publicationDate: string\n\n## Endpoints\n1. GET /books      → all books, 200 on success\n2. GET /books/:id  → one book, 200 on success, 404 if no match` },
        { type: 'code', title: 'Version 2 — precise and testable (excerpt)', lang: 'js', code: `## Data Model\nDatabase: cse341-books-db · Collection: books\n- id: string (required)\n- author: string (required)\n- title: string (required)\n- publicationDate: string, ISO 8601, e.g. "2021-08-17" (required)\n\n## Error Handling\n- Never return stack traces to clients.\n- 500 errors return: { "message": "Internal server error" }\n\n## Out of Scope for Week 1\n- POST, PUT, DELETE routes\n- Authentication and authorization` },
        { type: 'callout', variant: 'danger', title: 'Common mistake', body: 'Do not jump directly to coding. If your routes are unclear, pause and improve the spec first.' },
        { type: 'h', text: 'Part 2 — Create the plan (GitHub issues)' },
        { type: 'p', text: 'Turn the spec into a short ordered list of coding tasks, then create one GitHub issue per task. GitHub issues define scope, create a visible order of work, and support pull request tracking. Each issue needs a title, a task description, and a Test Plan with the exact checks needed to close it.' },
        { type: 'list', style: 'check', items: [
          'Clear — the task states exactly what should be built.',
          'Testable — you can verify success with specific checks.',
          'Small — focused enough to complete in one work session.',
          'Verifiable — the Test Plan explains how the task will be checked.',
        ]},
        { type: 'code', title: 'example issue structure', lang: 'js', code: `Title: Implement a route to retrieve one book by id\n\nDescription:\n- Create route for GET /books/:id\n- Return 200 with the book, 404 when missing, 500 on failure\n- Not found body: { "message": "Book not found" }\n\nTest Plan:\n- Existing id returns one book object in JSON\n- Missing id returns 404 with the message above\n- Response uses application/json\n- Unexpected failures return safe JSON with status 500` },
        { type: 'h', text: 'Part 3 — Implement with branches and pull requests' },
        { type: 'p', text: 'A pull request shows the changes you want so they can be reviewed and merged. You work on a separate feature branch, push it to GitHub, and request a merge into main. When merged, you pull the updated main down and delete the local feature branch.' },
        { type: 'code', title: 'the branch → PR → merge loop', lang: 'bash', code: `git switch -c get-book-by-id\n# ... implement, test, lint ...\ngit add .\ngit commit -m "Add GET /books/:id route"\ngit push origin get-book-by-id\n# Open PR → description includes "Closes #3" + verified test plan\n# Merge, then clean up:\ngit switch main\ngit pull origin main\ngit branch -d get-book-by-id` },
        { type: 'callout', variant: 'tip', title: 'Link PRs to issues automatically', body: 'When your PR description includes Resolves #N, Closes #N, or Fixes #N, GitHub links the PR to the issue and closes the issue automatically when the PR is merged.' },
        { type: 'h', text: 'The MVC pattern in an API' },
        { type: 'p', text: 'MVC stands for Model, View, Controller. In an API project, instead of returning rendered views, controllers return JSON data. The model retrieves data from MongoDB, the controller decides how to respond, and the router connects the URL to the controller function.' },
        { type: 'diagram', name: 'mvc', caption: 'Router → Controller → Model → MongoDB, and back with JSON.' },
        { type: 'code', title: 'src/models/books.js', lang: 'js', code: `import { getDb } from '../db/connect.js';\n\nconst getAllBooks = async () => {\n  const db = getDb();\n  const collection = db.collection('books');\n  const books = await collection.find({}).toArray();\n  return books;\n};\n\nconst getBookById = async (bookId) => {\n  const db = getDb();\n  return db.collection('books').findOne({ id: bookId });\n};\n\nexport { getAllBooks, getBookById };` },
        { type: 'code', title: 'src/controllers/books.js', lang: 'js', code: `import { getAllBooks, getBookById } from '../models/books.js';\n\nconst getBooksHandler = async (req, res) => {\n  try {\n    const books = await getAllBooks();\n    return res.status(200).json(books);\n  } catch (error) {\n    console.error('GET /books failed:', error.message);\n    return res.status(500).json({ message: 'Internal server error' });\n  }\n};\n\nconst getBookByIdHandler = async (req, res) => {\n  const requestedId = req.params.id;\n  try {\n    const book = await getBookById(requestedId);\n    if (!book) {\n      return res.status(404).json({ message: 'Book not found' });\n    }\n    return res.status(200).json(book);\n  } catch (error) {\n    console.error('GET /books/:id failed:', error.message);\n    return res.status(500).json({ message: 'Internal server error' });\n  }\n};\n\nexport { getBooksHandler, getBookByIdHandler };` },
        { type: 'code', title: 'src/router.js + app.js wiring', lang: 'js', code: `// src/router.js\nimport express from 'express';\nimport { getBooksHandler, getBookByIdHandler } from './controllers/books.js';\n\nconst router = express.Router();\n\nrouter.get('/books', getBooksHandler);\nrouter.get('/books/:id', getBookByIdHandler);\n\nexport default router;\n\n// app.js\nimport router from './src/router.js';\napp.use(express.json());\napp.use(router);` },
        { type: 'callout', variant: 'info', title: '404 is not 500', body: 'A missing record is not the same as a server failure. Return 404 for "not found" and reserve 500 for unexpected server problems.' },
        { type: 'h', text: 'Part 4 — Reflect' },
        { type: 'p', text: 'Good engineers do more than write and deliver code — they improve how they work. Reflection helps you notice patterns such as weak planning, missing checks, or better debugging habits. Strong reflections refer to specific evidence: a route file, a controller function, a GitHub issue, or a pull request.' },
        { type: 'takeaways', items: [
          'Spec first: endpoints, methods, inputs, outputs, status codes, error shapes.',
          'One GitHub issue per task, each with a Test Plan.',
          'Branch per issue → PR with Closes #N → merge → pull main → delete branch.',
          'MVC in an API: model talks to MongoDB, controller shapes the response, router maps URLs.',
          'Reflect with evidence, in your own words.',
        ]},
        { type: 'exercise', title: 'Mini-project: the Books Web Service', level: 'Stretch', steps: [
          'Write a Version 2 spec for a read-only Books API (GET /books and GET /books/:id) with JSON examples for 200, 404, and 500 responses.',
          'Create four GitHub issues: create collection + connect, GET /books, GET /books/:id, deploy and test.',
          'Implement each issue on its own branch with a model, controller, and route; merge each with a PR.',
          'Test with curl -i for a real id and a missing id; verify the status codes match your spec.',
          'Deploy to Render, add MONGODB_URI and MONGODB_DB_NAME env vars, whitelist Render IPs in Atlas, and verify the deployed endpoints.',
          'Write a one-page reflection citing your spec, issues, PRs, and deployed URL.',
        ]},
      ],
    },
  ],
  quiz: [
    { q: 'What is an API in relation to a web service?', options: ['The database the service uses', 'The contract describing routes, methods, inputs, outputs, and errors', 'A tool for minifying JSON', 'The HTTP server software'], answer: 1, explain: 'The API is the contract; the web service is the running code that follows it.' },
    { q: 'Which response shape best matches the web-services approach?', options: ['Fully rendered HTML pages', 'JSON data the client renders', 'CSV downloads', 'Binary streams only'], answer: 1, explain: 'Web services usually return data (JSON); clients decide how to present it.' },
    { q: 'A client requests GET /books/zzz and no such book exists. Which status code fits?', options: ['200', '201', '404', '500'], answer: 2, explain: 'A valid request for a missing resource is 404 Not Found.' },
    { q: 'Why split app.js from server.js?', options: ['It makes npm install faster', 'Tests can import the app without starting a real port', 'Express requires two files', 'It avoids using environment variables'], answer: 1, explain: 'Separation improves testability: app.js configures Express, server.js starts listening.' },
    { q: 'In MongoDB, a collection is…', options: ['A single stored record', 'A group of related documents', 'A 24-character hex string', 'A type of HTTP request'], answer: 1, explain: 'A document is one record; a collection groups related documents.' },
    { q: 'Which command auto-fixes safe ESLint problems?', options: ['npm run lint', 'npm run lint:fix', 'npm install eslint', 'node eslint.config.js'], answer: 1, explain: 'eslint . --fix applies automatic fixes such as var → const.' },
    { q: 'Where should production secrets live when deploying to Render?', options: ['In a committed .env file', 'In Render environment variable settings', 'In the README', 'Hard-coded in server.js'], answer: 1, explain: 'Secrets never go into Git; Render exposes env vars via process.env.' },
    { q: 'What does "Closes #3" in a PR description do?', options: ['Deletes branch #3', 'Links the PR to issue #3 and closes it on merge', 'Locks the repository', 'Runs the test suite'], answer: 1, explain: 'Keywords like Closes/Fixes/Resolves auto-link and close issues when the PR merges.' },
  ],
};
