import type { Module } from '../types';

export const week04: Module = {
  id: 'w4',
  week: 'Week 04',
  title: 'Authentication & Authorization',
  tagline: 'Prove who a user is, decide what they may do — with OAuth, JWTs, sessions, bcrypt, and middleware guards.',
  level: 'Advanced',
  hue: 330,
  related: ['w3', 'w5'],
  sections: [
    {
      id: 'authn-vs-authz',
      title: 'Authentication vs. Authorization',
      minutes: 30,
      blocks: [
        { type: 'lead', text: 'Authentication answers "Who is making this request?" Authorization answers "What is this authenticated user allowed to do?" Almost every serious web service needs both — and they are different questions with different status codes.' },
        { type: 'table', title: 'Two different questions', headers: ['Question', 'Concept', 'Example'], rows: [
          ['Who are you?', 'Authentication', 'A user signs in and the API identifies their user id.'],
          ['What are you allowed to do?', 'Authorization', 'An admin can update product inventory, but a customer cannot.'],
        ]},
        { type: 'p', text: 'Signing in with a school account is authentication. Checking whether that signed-in user can cancel an order is authorization. In an ecommerce API, authentication proves the request came from a real signed-in customer; authorization decides whether that customer can view an order, cancel an order, or access an admin route.' },
        { type: 'h', text: 'Sessions and tokens' },
        { type: 'list', style: 'plain', items: [
          'Session-based auth — the server stores session data and the browser keeps a session cookie. Common in traditional web apps because the browser automatically sends cookies.',
          'Token-based auth — the server gives the client a signed token; the client sends that token with later requests. Common in APIs because mobile apps, browser apps, and other services can all send tokens in request headers.',
        ]},
        { type: 'h', text: 'The protected-request flow' },
        { type: 'diagram', name: 'auth-guard', caption: 'Middleware checks credentials before the route handler runs.' },
        { type: 'list', style: 'steps', items: [
          'The client sends a request to a protected route.',
          'The request includes proof of authentication, such as a session cookie or bearer token.',
          'Authentication middleware checks the proof.',
          'Missing or invalid proof → 401 Unauthorized.',
          'Valid proof → the middleware attaches user information to the request.',
          'The route handler uses the user information to complete the request.',
          'Authenticated but not allowed → 403 Forbidden.',
        ]},
        { type: 'code', title: 'filtering data by the authenticated user', lang: 'js', code: `const getMyOrdersHandler = async (req, res) => {\n  try {\n    const orders = await Order.find({ user: req.user.id });\n    return res.status(200).json(orders);\n  } catch (error) {\n    return res.status(500).json({ message: 'Internal server error' });\n  }\n};` },
        { type: 'h', text: 'Status codes for auth' },
        { type: 'list', style: 'plain', items: [
          '401 Unauthorized — the request is not authenticated or credentials are invalid.',
          '403 Forbidden — the user is authenticated but does not have permission for the action.',
          '400 Bad Request — the authentication request is missing required input.',
          '500 Internal Server Error — something unexpected failed on the server.',
        ]},
        { type: 'table', title: 'Which routes need protection?', headers: ['Route', 'Purpose', 'Likely auth behavior'], rows: [
          ['GET /products', 'List public products', 'May be public'],
          ['GET /orders/me', "List current user's orders", 'Requires authentication'],
          ['POST /orders', 'Create an order', 'Requires authentication'],
          ['PUT /admin/products/:id', 'Update product inventory', 'Requires admin authorization'],
        ]},
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Authentication vs. authorization in one sentence each?', a: 'Authentication verifies who is making a request. Authorization determines whether that authenticated user may perform a particular action.' },
          { q: 'No valid credentials were sent. Status code?', a: '401 Unauthorized — the request is not authenticated or its credentials are invalid.' },
          { q: 'A signed-in customer calls an admin-only route. Status code?', a: '403 Forbidden — the user is authenticated but lacks permission.' },
        ]},
        { type: 'takeaways', items: [
          'Authentication = who; authorization = what they may do.',
          '401 for missing/invalid credentials; 403 for insufficient permission.',
          'Middleware attaches req.user; controllers filter data by it.',
          'A role check is not enough for ownership — query only the user\'s own records.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: classify routes', level: 'Warm-up', steps: [
          'List five routes from a shop API (e.g. GET /products, POST /orders, GET /orders/me, DELETE /admin/users/:id, POST /login).',
          'For each, label it public, authenticated, or admin-only.',
          'For each protected route, write what should happen when no token is sent and when the wrong role is sent.',
        ]},
      ],
    },
    {
      id: 'oauth-jwt',
      title: 'OAuth & JSON Web Tokens',
      minutes: 40,
      blocks: [
        { type: 'lead', text: 'OAuth lets users sign in through a trusted identity provider without your app ever touching their password. JWTs are signed tokens that carry claims about a user — the backbone of token-based API authentication.' },
        { type: 'h', text: 'The OAuth authorization code flow' },
        { type: 'p', text: 'OAuth is a standard that allows a user to grant access through a trusted identity provider. Many "Sign in with Google" or "Sign in with GitHub" flows use OAuth. The browser is redirected back and forth automatically because of 300-level status codes that tell it to redirect.' },
        { type: 'diagram', name: 'oauth-flow', caption: 'The authorization code flow between browser, application, and OAuth provider.' },
        { type: 'list', style: 'steps', items: [
          'The user clicks a sign-in button in your app.',
          'The app redirects the user to the identity provider (302).',
          'The user signs in at the provider and grants permission.',
          'The provider redirects back to your app with a temporary code.',
          'The app exchanges the code for tokens and user profile information.',
          'The app creates its own authenticated state (a session or its own token).',
        ]},
        { type: 'callout', variant: 'info', title: 'OAuth is not just "login"', body: 'OAuth is about delegated access. The important idea is that your app never handles the user\'s external-provider password — it receives a temporary code and exchanges that for tokens or user information.' },
        { type: 'callout', variant: 'warn', title: 'Callback URLs must match exactly', body: 'OAuth providers require an exact callback URL. http://localhost:3000/auth/callback is different from your Render callback URL. If the callback URL is wrong, login fails even when the code is otherwise correct. Client id, client secret, callback URL, and provider URLs belong in environment variables.' },
        { type: 'h', text: 'Anatomy of a JWT' },
        { type: 'p', text: 'A JSON Web Token is a signed string that carries claims about a user or request. Claims might include a user id, email, role, or expiration time. A JWT has three parts: a header (metadata and signing algorithm), a payload (claims), and a signature (proof the token was signed by a trusted secret).' },
        { type: 'diagram', name: 'jwt-structure', caption: 'Header · Payload · Signature — encoded, signed, but not encrypted.' },
        { type: 'code', title: 'a JWT payload', lang: 'json', code: `{\n  "sub": "64f1a2...",\n  "email": "customer@example.com",\n  "role": "customer",\n  "exp": 1760000000\n}` },
        { type: 'list', style: 'plain', items: [
          'sub — the subject, usually the user\'s unique id.',
          'email — a claim identifying the user.',
          'role — a custom claim used for authorization decisions.',
          'exp — expiration time as a Unix timestamp.',
        ]},
        { type: 'callout', variant: 'danger', title: 'The payload is encoded, not encrypted', body: 'Clients may be able to read the claims. Never put passwords, secrets, or sensitive personal information inside a JWT payload.' },
        { type: 'h', text: 'Signing and verifying' },
        { type: 'code', title: 'create and verify a token', lang: 'js', code: `import jwt from 'jsonwebtoken';\n\nconst createToken = (user) => {\n  if (!process.env.JWT_SECRET) {\n    throw new Error('JWT_SECRET is required.');\n  }\n\n  return jwt.sign(\n    { sub: user._id.toString(), email: user.email, role: user.role },\n    process.env.JWT_SECRET,\n    { expiresIn: '1h' }\n  );\n};\n\nconst decoded = jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] });` },
        { type: 'p', text: 'If verification succeeds, the decoded claims identify the user. If it fails, the API should reject the request with a safe 401 response. The signing secret should be long, random, stored in environment variables, and different from any example value in course materials.' },
        { type: 'code', title: 'sending the token', lang: 'http', code: `GET /orders/me HTTP/1.1\nAuthorization: Bearer <token>` },
        { type: 'callout', variant: 'warn', title: 'Claims can go stale', body: 'Claims such as role can become outdated if a user\'s permissions change after the token is created. For sensitive authorization decisions, check current user data from the server-side database instead of trusting an old token claim by itself.' },
        { type: 'h', text: 'JWT authentication middleware' },
        { type: 'code', title: 'requireAuth middleware', lang: 'js', code: `import jwt from 'jsonwebtoken';\n\nconst requireAuth = (req, res, next) => {\n  const authHeader = req.headers.authorization;\n\n  if (!authHeader || !authHeader.startsWith('Bearer ')) {\n    return res.status(401).json({ message: 'Authentication required' });\n  }\n\n  const token = authHeader.split(' ')[1];\n\n  if (!process.env.JWT_SECRET) {\n    return next(new Error('Authentication configuration error.'));\n  }\n\n  try {\n    const decoded = jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] });\n    req.user = { id: decoded.sub, email: decoded.email, role: decoded.role };\n    return next();\n  } catch (error) {\n    return res.status(401).json({ message: 'Invalid or expired token' });\n  }\n};` },
        { type: 'code', title: 'protecting routes with roles', lang: 'js', code: `const requireRole = (role) => {\n  return (req, res, next) => {\n    if (!req.user || req.user.role !== role) {\n      return res.status(403).json({ message: 'Forbidden' });\n    }\n    return next();\n  };\n};\n\nrouter.get('/orders/me', requireAuth, getMyOrdersHandler);\nrouter.put('/admin/products/:id', requireAuth, requireRole('admin'), updateProductHandler);` },
        { type: 'p', text: 'This pattern separates authentication from authorization: first the API verifies who the user is, then it checks whether that user has the required role.' },
        { type: 'demo', name: 'jwt-lab' },
        { type: 'h', text: 'Document protected routes in Swagger' },
        { type: 'p', text: 'Protected routes can still be documented and tested through Swagger, but the docs must describe how to provide authentication — typically a bearer token security scheme — and explicitly document the 401, 403, and success responses so others know what to expect.' },
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Why use an OAuth authorization code instead of the user\'s provider password?', a: 'The provider handles the password; your app exchanges a temporary code for tokens or user info and never stores or processes the external password.' },
          { q: 'Why store secrets and callback configuration in environment variables?', a: 'They keep sensitive, deployment-specific values out of source code and let local and deployed environments use different configuration safely.' },
          { q: 'Is a JWT payload private?', a: 'No. It is encoded, not encrypted — anyone holding the token can read the claims. Never put secrets in it.' },
        ]},
        { type: 'takeaways', items: [
          'OAuth delegates sign-in to a provider via redirect + authorization code.',
          'JWT = header + payload + signature; signed, not encrypted.',
          'Bearer tokens travel in the Authorization header; middleware verifies and attaches req.user.',
          'requireAuth answers 401; requireRole answers 403; combine both on admin routes.',
        ]},
        { type: 'exercise', title: 'Mini-exercise: decode a JWT', level: 'Warm-up', steps: [
          'Use the JWT lab above: edit the payload claims and watch the token parts change.',
          'Identify the three parts of the token string and what each contains.',
          'Write down why changing one character of the payload breaks the signature.',
          'List three things that must never appear in a JWT payload.',
        ]},
      ],
    },
    {
      id: 'session-auth',
      title: 'Session Authentication & Middleware',
      minutes: 40,
      blocks: [
        { type: 'lead', text: 'For a browser application with EJS pages plus same-origin API calls, session-based authentication is a practical, professional choice: after sign-in, the browser automatically sends its session cookie with every request.' },
        { type: 'h', text: 'JWTs compared with sessions' },
        { type: 'p', text: 'JWTs are strong for purely API-based applications with mobile clients or separate frontends — but the client must store the token and attach it to every request. Sessions fit browser apps better: the cookie travels automatically, so client-side JavaScript never manages a bearer token. Both follow the same pattern: the user sends credentials, the server verifies them, the server issues a token of some kind, and later requests present it.' },
        { type: 'code', title: 'install + generate a session secret', lang: 'bash', code: `npm install express-session\nnpm install bcrypt\n\nnode -e "console.log(require('crypto').randomBytes(64).toString('hex'))"\n# .env → SESSION_SECRET=your_generated_secret_here\n# also add SESSION_SECRET in Render's environment settings` },
        { type: 'code', title: 'session middleware configuration', lang: 'js', code: `import session from 'express-session';\n\nconst SESSION_SECRET = process.env.SESSION_SECRET;\n\napp.use(session({\n  secret: SESSION_SECRET,\n  resave: false,\n  saveUninitialized: false,\n  rolling: true,\n  cookie: { maxAge: 60 * 60 * 1000 } // 1 hour of inactivity\n}));` },
        { type: 'list', style: 'plain', items: [
          'saveUninitialized: false — anonymous visitors do not get a stored session until something (like a login) is saved.',
          'rolling: true — the cookie expiration resets on every response, so the one hour is measured from the most recent activity.',
          'The cookie contains a session identifier — never the user\'s password.',
        ]},
        { type: 'callout', variant: 'warn', title: 'Middleware order matters', body: 'Express runs middleware in order. Register the session middleware before any route or middleware that uses req.session — put it after the routes and req.session will not exist when they run.' },
        { type: 'h', text: 'User and role models' },
        { type: 'code', title: 'role and user schemas', lang: 'js', code: `const roleSchema = new mongoose.Schema({\n  name: { type: String, enum: ['customer', 'admin'], unique: true, required: true }\n});\nexport const Role = mongoose.model('Role', roleSchema);\n\nconst userSchema = new mongoose.Schema({\n  name:         { type: String, required: true },\n  email:        { type: String, required: true, unique: true, lowercase: true },\n  passwordHash: { type: String, required: true },\n  role:         { type: mongoose.Schema.Types.ObjectId, ref: 'Role', required: true }\n});\nexport const User = mongoose.model('User', userSchema);` },
        { type: 'callout', variant: 'tip', title: 'Why reference a role?', body: 'Many users can have one role, and changing what a role means does not require rewriting every user document. Use populate(\'role\') when you need the role name during sign-in. Catch duplicate-key errors on registration and return a friendly message rather than a raw MongoDB error.' },
        { type: 'h', text: 'Passwords are hashed, never stored in plain text' },
        { type: 'code', title: 'hash and verify with bcrypt', lang: 'js', code: `import bcrypt from 'bcrypt';\n\n// register\nconst passwordHash = await bcrypt.hash(req.body.password, 12);\nconst user = await User.create({ email: req.body.email, passwordHash, role: 'customer' });\n\n// login\nconst passwordMatches = await bcrypt.compare(req.body.password, user.passwordHash);` },
        { type: 'callout', variant: 'danger', title: 'Never store plain-text passwords', body: 'A hash is not encryption — the goal is not to recover the original password, but to verify that a later attempt produces the expected hash. Plain-text passwords must never be committed, logged, returned in API responses, or stored in the database.' },
        { type: 'h', text: 'Model functions for auth' },
        { type: 'code', title: 'createUser / findUserByEmail / verifyPassword', lang: 'js', code: `const createUser = async (name, email, password) => {\n  const customer = await Role.findOne({ name: 'customer' });\n  if (!customer) throw new Error('Default role not found');\n\n  const passwordHash = await bcrypt.hash(password, 12);\n  const user = await User.create({ name, email, passwordHash, role: customer._id });\n  return user._id.toString();\n};\n\nconst findUserByEmail = async (email) => {\n  return User.findOne({ email }).populate('role');\n};\n\nconst verifyPassword = async (password, passwordHash) => {\n  return bcrypt.compare(password, passwordHash);\n};` },
        { type: 'callout', variant: 'warn', title: 'Assign the role on the server', body: 'Public registration must always assign the customer role on the server. A browser request cannot be trusted to choose its own access level — otherwise a visitor could submit a form that grants them the admin role.' },
        { type: 'h', text: 'Store the user in the session, then guard routes' },
        { type: 'code', title: 'after a successful login', lang: 'js', code: `req.session.user = {\n  id: user._id.toString(),\n  name: user.name,\n  role: user.role.name // 'customer' or 'admin'\n};\nres.redirect('/account');` },
        { type: 'code', title: 'middleware: loader + four guards', lang: 'js', code: `export const loadSessionUser = (req, res, next) => {\n  req.user = req.session.user || null;\n  res.locals.user = req.user;\n  next();\n};\n\nconst isLoggedIn = (req) => Boolean(req.user);\nconst hasRole = (req, role) => req.user.role === role;\n\nexport const requireApiLogin = (req, res, next) => {\n  if (!isLoggedIn(req)) {\n    return res.status(401).json({ message: 'Authentication required' });\n  }\n  next();\n};\n\nexport const requirePageLogin = (req, res, next) => {\n  if (!isLoggedIn(req)) {\n    return res.redirect('/login');\n  }\n  next();\n};\n\nexport const requireApiRole = (role) => (req, res, next) => {\n  if (!isLoggedIn(req)) return res.status(401).json({ message: 'Authentication required' });\n  if (!hasRole(req, role)) return res.status(403).json({ message: 'Forbidden' });\n  next();\n};\n\nexport const requirePageRole = (role) => (req, res, next) => {\n  if (!isLoggedIn(req)) return res.redirect('/login');\n  if (!hasRole(req, role)) return res.status(403).render('error', { message: 'Forbidden' });\n  next();\n};` },
        { type: 'p', text: 'The two login guards do the same check but respond differently: a protected EJS page redirects to the login page; a protected API returns JSON with status 401 so client-side JavaScript can handle it. Register loadSessionUser after the session middleware and before any routes.' },
        { type: 'code', title: 'apply the matching guard to each route', lang: 'js', code: `// Page routes: render EJS or redirect to login\nrouter.get('/account', requirePageLogin, accountPage);\nrouter.get('/admin/users', requirePageRole('admin'), adminUsersPage);\n\n// API routes: send JSON errors that fetch() can inspect\napiRouter.get('/orders/me', requireApiLogin, getMyOrders);\napiRouter.delete('/projects/:id', requireApiRole('admin'), deleteProject);` },
        { type: 'callout', variant: 'danger', title: 'Server-side checks are required', body: 'Hiding an admin link in an EJS page improves the experience, but it does not secure the route. Enforce authentication, roles, and ownership on the server for every protected page and API route.' },
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Why are sessions a good fit for this project?', a: 'The project uses browser-rendered EJS pages and same-origin API requests; after sign-in the browser sends the session cookie automatically, so no client-side token management is needed.' },
          { q: 'What is SESSION_SECRET for?', a: 'It signs the session ID cookie to protect session data. It must be long, random, stored in an environment variable, and never committed.' },
          { q: 'How does an unauthenticated request differ for a page vs. an API route?', a: 'A protected page redirects the browser to /login; a protected API returns JSON 401 Unauthorized.' },
          { q: 'Why is a role check not enough for order details?', a: 'Role middleware confirms the requester is a customer, but the controller must also verify ownership by querying only orders belonging to that user id.' },
        ]},
        { type: 'takeaways', items: [
          'Sessions fit browser apps; JWTs fit decoupled API clients.',
          'bcrypt.hash on register, bcrypt.compare on login — never store plain text.',
          'loadSessionUser copies the session to req.user; guards call next() only when allowed.',
          'Pages redirect on failure; APIs return 401/403 JSON.',
        ]},
        { type: 'exercise', title: 'Mini-project: protect a route pair', level: 'Core', steps: [
          'Configure express-session with a generated SESSION_SECRET in .env.',
          'Create Role and User schemas; seed customer and admin roles.',
          'Build register/login/logout controllers using createUser, findUserByEmail, verifyPassword.',
          'Write requirePageLogin and requireApiLogin middleware; protect one page and one API route.',
          'Test: logged-out page visit redirects; logged-out API call returns JSON 401.',
        ]},
      ],
    },
    {
      id: 'api-update-delete-frontend',
      title: 'Updating & Deleting through APIs',
      minutes: 35,
      blocks: [
        { type: 'lead', text: 'When a browser needs to update or delete an item, it calls the web service to make the change, then updates just the affected part of the page — no full reload. The API owns the data; the browser owns the experience.' },
        { type: 'h', text: 'The interaction plan' },
        { type: 'list', style: 'steps', items: [
          'Load products with GET /api/products.',
          'Render each product with Edit and Delete buttons.',
          'Edit replaces only the selected card with an edit form.',
          'Save sends PUT /api/products/:id; Delete sends DELETE /api/products/:id.',
          'Use the successful response to update the list — never window.location.reload().',
        ]},
        { type: 'callout', variant: 'warn', title: 'Wait for the server', body: 'Do not assume a local edit succeeded just because a user clicked Save. The server may reject the request because the product is missing, the values are invalid, or the user lacks permission. The browser should wait for the API response before changing the displayed data.' },
        { type: 'h', text: 'Two templates: display and edit' },
        { type: 'code', title: 'HTML with card + edit templates', lang: 'html', code: `<p id="product-message"></p>\n<h2>Products</h2>\n<div id="product-list"></div>\n\n<template id="product-card-template">\n  <div class="product-card" data-product-id="">\n    <h3 class="product-name"></h3>\n    <p class="product-category"></p>\n    <p class="product-price"></p>\n    <button type="button" data-action="edit">Edit</button>\n    <button type="button" data-action="delete">Delete</button>\n  </div>\n</template>\n\n<template id="product-edit-template">\n  <form class="product-edit-form" data-product-id="">\n    <label>Name <input name="name" required></label>\n    <label>Category <input name="category" required></label>\n    <label>Price <input name="price" type="number" min="0" step="0.01" required></label>\n    <button type="submit">Save</button>\n    <button type="button" data-action="cancel">Cancel</button>\n  </form>\n</template>` },
        { type: 'h', text: 'Keep products in a Map; delegate events' },
        { type: 'code', title: 'render from a Map, listen on the container', lang: 'js', code: `const productList = document.querySelector('#product-list');\nlet productsById = new Map();\n\nasync function loadProducts() {\n  const response = await fetch('/api/products');\n  if (!response.ok) throw new Error('Unable to load products.');\n  const products = await response.json();\n  productsById = new Map(products.map((product) => [product._id, product]));\n  renderProducts();\n}\n\n// One listener on the stable container handles every card's buttons\nproductList.addEventListener('click', async (event) => {\n  const button = event.target.closest('button[data-action]');\n  if (!button) return;\n  const card = button.closest('[data-product-id]');\n  const product = productsById.get(card.dataset.productId);\n\n  if (button.dataset.action === 'edit') showEditor(card, product);\n  if (button.dataset.action === 'cancel') renderProducts();\n  if (button.dataset.action === 'delete') await deleteProduct(product);\n});` },
        { type: 'callout', variant: 'tip', title: 'Why event delegation?', body: 'Rendered cards are replaced frequently. Instead of adding a listener to every new button, add one listener to the stable list container. Click events bubble up; closest() finds the selected button and its card. Listeners never need to be recreated after a render.' },
        { type: 'h', text: 'Save with PUT; delete with DELETE' },
        { type: 'code', title: 'saveProduct — preventDefault, PUT, then re-render', lang: 'js', code: `async function saveProduct(event) {\n  event.preventDefault();\n  const form = event.currentTarget;\n  const body = Object.fromEntries(new FormData(form));\n  body.price = Number(body.price);\n\n  const response = await fetch(\n    \`/api/products/\${encodeURIComponent(form.dataset.productId)}\`,\n    { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }\n  );\n\n  if (!response.ok) {\n    message.textContent = 'The product could not be updated.';\n    return;\n  }\n\n  const updated = await response.json();\n  productsById.set(updated._id, updated);\n  renderProducts();\n  message.textContent = \`\${updated.name} was updated.\`;\n}` },
        { type: 'code', title: 'deleteProduct — confirm, DELETE, then re-render', lang: 'js', code: `async function deleteProduct(product) {\n  if (!window.confirm(\`Delete \${product.name}?\`)) return;\n\n  const response = await fetch(\n    \`/api/products/\${encodeURIComponent(product._id)}\`,\n    { method: 'DELETE' }\n  );\n\n  if (!response.ok) {\n    message.textContent = 'The product could not be deleted.';\n    return;\n  }\n\n  productsById.delete(product._id);\n  renderProducts();\n  message.textContent = \`\${product.name} was deleted.\`;\n}` },
        { type: 'callout', variant: 'info', title: 'Confirmation is not authorization', body: 'A confirmation dialog helps prevent accidental deletion, but the server must still check the signed-in user\'s role or ownership before removing a product. Browser values are never secure — a user can change DOM attributes — so everything must be validated on the server.' },
        { type: 'h', text: 'Protect the API on the server' },
        { type: 'code', title: 'guarded update route with allowed fields', lang: 'js', code: `router.put('/products/:id', requireApiRole('admin'), updateProduct);\nrouter.delete('/products/:id', requireApiRole('admin'), deleteProduct);\n\nexport async function updateProduct(req, res) {\n  try {\n    const allowedUpdates = {};\n    if (req.body.name !== undefined) allowedUpdates.name = req.body.name;\n    if (req.body.price !== undefined) allowedUpdates.price = req.body.price;\n    if (req.body.category !== undefined) allowedUpdates.category = req.body.category;\n    if (req.body.isActive !== undefined) allowedUpdates.isActive = req.body.isActive;\n\n    const product = await Product.findByIdAndUpdate(\n      req.params.id,\n      allowedUpdates,\n      { new: true, runValidators: true }\n    );\n    if (!product) return res.status(404).json({ message: 'Product not found.' });\n    return res.status(200).json(product);\n  } catch (error) {\n    if (error.name === 'CastError') {\n      return res.status(400).json({ message: 'Invalid product id.' });\n    }\n    return res.status(500).json({ message: 'Unable to update product.' });\n  }\n}` },
        { type: 'list', style: 'check', items: [
          '401 — missing or invalid login.',
          '403 — signed in but without permission.',
          '400 — invalid input, including an invalid id format.',
          '404 — the product does not exist.',
          'Never return raw database errors to the browser.',
        ]},
        { type: 'qa', title: 'Check your understanding', items: [
          { q: 'Why wait for the API response before changing the list?', a: 'The API may reject the request for validation, authorization, or a missing record. Waiting keeps displayed state aligned with server data.' },
          { q: 'Why use HTML templates?', a: 'They keep reusable markup in HTML and let JavaScript clone and fill elements safely without large HTML strings.' },
          { q: 'Why event delegation?', a: 'One listener handles buttons in current and newly rendered cards — no re-binding after every render.' },
          { q: 'Confirmation vs. authorization?', a: 'Confirmation prevents accidental actions; server authorization determines whether the action is actually allowed.' },
        ]},
        { type: 'takeaways', items: [
          'The API validates, authorizes, and writes; the browser renders and collects input.',
          'Use the API response — not the submitted form values — to update the UI.',
          'Templates + a Map + event delegation = a clean, refresh-free editing experience.',
          'Every write route needs server-side guards and allowed-field updates.',
        ]},
        { type: 'exercise', title: 'Mini-project: in-place editing list', level: 'Stretch', steps: [
          'Build a product list page that loads via GET /api/products into a Map.',
          'Render cards from a display template with Edit/Delete buttons (data-action, data-product-id).',
          'Implement the edit template swap, PUT save flow, and DELETE flow with confirmation.',
          'Protect PUT/DELETE with requireApiRole(\'admin\') and verify 401/403 responses appear as messages in the UI.',
          'Confirm the page never calls window.location.reload().',
        ]},
      ],
    },
  ],
  quiz: [
    { q: 'Authentication answers which question?', options: ['What is this user allowed to do?', 'Who is making this request?', 'How fast is the server?', 'Which database should store the user?'], answer: 1, explain: 'Authentication proves identity; authorization decides permissions.' },
    { q: 'A signed-in customer calls an admin-only route. Correct status?', options: ['401', '403', '404', '500'], answer: 1, explain: 'Authenticated but not allowed → 403 Forbidden.' },
    { q: 'A request arrives with no credentials at all. Correct status?', options: ['400', '401', '403', '200'], answer: 1, explain: 'Missing or invalid authentication → 401 Unauthorized.' },
    { q: 'In the OAuth flow, what does your app receive from the provider first?', options: ['The user\'s password', 'A temporary authorization code', 'A session cookie', 'The user\'s private key'], answer: 1, explain: 'The app exchanges the code for tokens — it never sees the external password.' },
    { q: 'A JWT payload is…', options: ['Encrypted end-to-end', 'Encoded and readable by the client — never put secrets in it', 'Invisible to browsers', 'Stored in MongoDB automatically'], answer: 1, explain: 'The payload is Base64-encoded, not encrypted. Signature proves integrity, not secrecy.' },
    { q: 'Why bcrypt instead of encryption for passwords?', options: ['It is faster', 'Hashes verify attempts without ever recovering the original password', 'It compresses passwords', 'It works without a secret'], answer: 1, explain: 'The goal is verification, not recovery — plain-text passwords are never stored.' },
    { q: 'For a protected EJS page, an unauthenticated visitor should get…', options: ['JSON 401', 'A redirect to /login', 'Status 204', 'A stack trace'], answer: 1, explain: 'Pages redirect; API routes return JSON 401 so fetch() can handle it.' },
    { q: 'Why wait for the API response before updating the displayed list?', options: ['It looks nicer', 'The server may reject the change — the UI must reflect server state', 'fetch requires it', 'To save bandwidth'], answer: 1, explain: 'Validation, authorization, or a missing record can reject the request; optimistic UI would lie to the user.' },
  ],
};
